// Sanctuary Grimoire Design System
// Each class has a unique color theme applied site-wide when selected

export interface MetaBuild {
  name: string;
  description: string;
  keyItems: string[];
  tier: "S" | "A" | "B";
  playstyle: string;
}

export interface Ability {
  name: string;
  description: string;
  type: string;
  element?: string;
  keybind?: string;       // Recommended key binding (e.g. "LMB", "RMB", "1", "2", "3", "4")
  keybindNote?: string;  // Why this key is recommended
}

export interface LevelingTips {
  early: string[];   // 1-30
  mid: string[];     // 31-60
  late: string[];    // 61-70
  endgame: string[]; // 70+
}

export interface SkillBarSlot {
  key: "LMB" | "RMB" | "1" | "2" | "3" | "4";
  abilityName: string;
  rune: string;          // Recommended rune for this slot
  element?: string;
  role: string;          // e.g. "Primary Generator", "Main Damage", "Mobility", "Buff", "Cooldown"
  note: string;          // Why this ability is on this key
}

export interface RotationStep {
  step: number;
  keys: string[];        // Keys pressed in this step, e.g. ["T", "3"]
  action: string;        // Short label, e.g. "Activate Wrath of the Berserker"
  detail: string;        // Full explanation of what this step does and why
  timing: "opener" | "on-cooldown" | "spam" | "situational" | "maintain";
}

export interface ClassData {
  id: string;
  name: string;
  tagline: string;
  overview: string;
  primaryStat: string;
  resource: { name: string; description: string };
  color: string;
  colorName: string;
  bgGradient: string;
  weaponTypes: string[];
  metaBuilds: MetaBuild[];
  abilities: Ability[];
  levelingTips: LevelingTips;
  masteryNote: string;
  masteryTips: string[];
  paragons: { category: string; priority: string[] }[];
  skillBar: SkillBarSlot[];   // The 6-slot recommended skill bar layout
  rotation: RotationStep[];   // Step-by-step rotation guide
}

export const classes: ClassData[] = [
  {
    id: "barbarian",
    name: "Barbarian",
    tagline: "Savage Wanderer of the Steppes",
    overview:
      "Barbarians are savage wanderers who excel in close-quarters combat, utilizing mighty ground stomps, leaping attacks, and dual-wielded slashes to decimate foes. They are ruthless brawlers who build up Fury through combat to unleash massive, sweeping strikes. While they have strong solo pushing builds, Barbarians are often essential support in group play due to their monstrous pulling abilities.",
    primaryStat: "Strength",
    resource: {
      name: "Fury",
      description:
        "Fury is generated by dealing and taking damage, as well as through Primary skills. It depletes slowly outside of combat. Key skills like War Cry, Threatening Shout, and Furious Charge help maintain Fury during intense fights.",
    },
    color: "#c0392b",
    colorName: "Volcanic Red",
    bgGradient: "linear-gradient(135deg, #1a0505 0%, #3d0a0a 50%, #1a0505 100%)",
    weaponTypes: [
      "Mighty Weapons (one-handed and two-handed) — Barbarian-exclusive, often with powerful legendary affixes",
      "Swords, Axes, Maces, Spears, Polearms",
      "Can dual-wield any two one-handed weapons",
      "Can equip shields for defensive builds",
    ],
    metaBuilds: [
      {
        name: "Wrath of the Wastes WW/Rend",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "The iconic Whirlwind Barbarian. Spin through enemy packs applying Rend's devastating bleed while the Wrath of the Wastes set amplifies every rotation. One of the most satisfying builds in the game.",
        keyItems: ["Wrath of the Wastes (6-piece)", "Ambo's Pride", "Lamentation", "Mortick's Brace", "Bul-Kathos's Oath"],
      },
      {
        name: "Immortal King's HotA",
        tier: "S",
        playstyle: "GR Push",
        description:
          "Maintains permanent Wrath of the Berserker and Call of the Ancients uptime, then unleashes devastating Hammer of the Ancients strikes. A cornerstone build for solo pushing.",
        keyItems: ["Immortal King's Call (6-piece)", "Bracers of the First Men", "The Gavel of Judgment", "Mortick's Brace", "Fury of the Ancients"],
      },
      {
        name: "Might of the Earth Leapquake",
        tier: "A",
        playstyle: "GR Push / Fun",
        description:
          "Leap repeatedly to trigger Earthquakes, then use Ground Stomp to reset Leap's cooldown. Lut Socks is the key item that makes this loop possible. Extremely satisfying to play.",
        keyItems: ["Might of the Earth (6-piece)", "Lut Socks", "Blade of the Tribes", "Girdle of Giants", "Seismic Slam"],
      },
    ],
    abilities: [
      { name: "Frenzy", type: "Primary", element: "Physical", keybind: "LMB", keybindNote: "Primary skills are always on Left Mouse Button for constant use and movement.", description: "Rapidly attacks enemies, generating Fury and stacking a damage buff with each hit. Core to several high-tier builds." },
      { name: "Whirlwind", type: "Fury Spender", element: "Physical", keybind: "RMB", keybindNote: "Right Mouse Button for your main damage skill — allows spinning while clicking toward enemies.", description: "Spin through enemy packs dealing continuous damage. The centerpiece of the WW/Rend build." },
      { name: "Hammer of the Ancients", type: "Fury Spender", element: "Physical", keybind: "RMB", keybindNote: "Right Mouse Button for your primary damage spender — easy to spam rapidly.", description: "Calls down a massive hammer dealing heavy area damage. The core skill of the IK HotA build." },
      { name: "Rend", type: "Fury Spender", element: "Physical", keybind: "1", keybindNote: "Slot 1 for quick access — in WW builds this is auto-applied by Ambo's Pride, so it can be on any slot.", description: "Causes enemies to bleed for massive damage over time. Applied automatically by Ambo's Pride while Whirlwinding." },
      { name: "Leap", type: "Technique", element: "Physical", keybind: "2", keybindNote: "Slot 2 for easy reach — Leapquake builds spam this constantly, so keep it accessible.", description: "Jump to a location, slamming the ground. With Lut Socks, generates up to 3 charges and triggers Earthquakes." },
      { name: "Earthquake", type: "Technique", element: "Fire", keybind: "3", keybindNote: "Slot 3 — used on cooldown after Leap, so proximity to Leap key (2) is ideal.", description: "Creates a massive tremor dealing fire damage. The core damage skill of the Leapquake build." },
      { name: "Furious Charge", type: "Technique", element: "Physical", keybind: "2", keybindNote: "Slot 2 for mobility — used frequently between packs, so easy reach is essential.", description: "Charge through enemies dealing damage. Used for mobility, Fury generation, and as a damage skill in the Raekor build." },
      { name: "War Cry", type: "Shout", element: "None", keybind: "3", keybindNote: "Slot 3 — used on cooldown for the Fury and Armor buff; doesn't need to be instantly accessible.", description: "Provides significant Armor and Fury. Almost universally used across all Barbarian builds for its defensive value." },
      { name: "Threatening Shout", type: "Shout", element: "None", keybind: "4", keybindNote: "Slot 4 — support shout used on cooldown; furthest slot is fine since it's not reaction-based.", description: "Reduces enemy damage dealt. Used in support (zBarb) builds and some solo builds for toughness." },
      { name: "Wrath of the Berserker", type: "Warcry", element: "None", keybind: "T", keybindNote: "Bind to T or a mouse thumb button — used on cooldown and needs to be instantly accessible for emergencies.", description: "Massive offensive buff providing increased attack speed, crit chance, and dodge. Maintained permanently in IK builds." },
      { name: "Ancient Spear", type: "Technique", element: "Physical", keybind: "1", keybindNote: "Slot 1 for zBarb — Rage Flip is your most-used skill in support role, needs to be fastest to reach.", description: "Throws a spear to pull enemies. The Rage Flip rune is essential for the support Barbarian (zBarb) role in group play." },
      { name: "Call of the Ancients", type: "Warcry", element: "Physical", keybind: "4", keybindNote: "Slot 4 — summoned once and maintained; doesn't need prime real estate on your bar.", description: "Summons three ancient warriors to fight alongside you. Required for the IK set bonus activation." },
    ],
    levelingTips: {
      early: [
        "Use Cleave or Frenzy as your primary skill for consistent Fury generation and damage.",
        "Equip War Cry early — the Impunity rune provides All Resistances, dramatically improving survivability.",
        "Prioritize two-handed weapons for raw damage; the higher damage range makes leveling faster.",
        "Ignore Vitality on gear — Strength provides Armor, and your natural toughness is sufficient early on.",
        "Use Ignore Pain with the Iron Hide rune when things get tough — it's a lifesaver in dense packs.",
      ],
      mid: [
        "Unlock and use Whirlwind once you have enough Fury generation to sustain it.",
        "Start looking for Mighty Weapons — they have Barbarian-specific legendary affixes that are build-defining.",
        "Equip Battle Rage for a consistent damage boost; the Marauder's Rage rune is excellent.",
        "Begin using Furious Charge for mobility between packs — it dramatically speeds up leveling.",
        "Look for items with Strength, Critical Hit Chance, and Critical Hit Damage as secondary priorities.",
      ],
      late: [
        "Focus on completing the Season Journey chapters to earn Haedrig's Gift (a free 6-piece set).",
        "Run Nephalem Rifts on the highest Torment you can clear in under 5 minutes for efficient gear drops.",
        "Use Kanai's Cube to upgrade Rare Mighty Weapons into Legendaries — the item pool is small and targeted.",
        "Prioritize getting your 2-piece and 4-piece set bonuses before pushing to Torment VI+.",
        "Start gambling Blood Shards at Kadala for Bracers and Belts — these slots have strong build-enabling legendaries.",
      ],
      endgame: [
        "Allocate Paragon points: Movement Speed cap first, then Main Stat (Strength) for damage.",
        "In the Offense category, prioritize Critical Hit Damage, then Critical Hit Chance.",
        "Area Damage is crucial for group play and dense pack situations — stack it on gear.",
        "For WW/Rend, maintain permanent Rend uptime — Ambo's Pride applies it automatically while spinning.",
        "The zBarb support role in 4-player groups requires mastering Ancient Spear Rage Flip for pixel-pulling.",
        "Push Greater Rifts by fishing for favorable maps (Battlefield of Eternity, Festering Woods) and elite-dense layouts.",
      ],
    },
    masteryNote:
      "The support Barbarian (zBarb) is one of the most skill-intensive roles in the game. Mastering Ancient Spear Rage Flip to pixel-pull monster packs into tight clusters for your damage dealers is an art form that separates good players from great ones.",
    masteryTips: [
      "Learn to 'pixel-pull' — use Ancient Spear Rage Flip to drag monsters into a single pixel for maximum Area Damage.",
      "In WW/Rend, never stop spinning — movement generates Rend stacks and maintains the Wastes set bonus.",
      "For IK HotA, use Furious Charge to reset Wrath of the Berserker cooldown via the Obsidian Ring of the Zodiac.",
      "Manage Fury carefully in HotA builds — spending Fury with Hammer of the Ancients while maintaining WotB uptime is the core loop.",
      "In Leapquake, always have 3 Leap charges ready before engaging a large elite pack for maximum burst damage.",
    ],
    paragons: [
      { category: "Core", priority: ["Movement Speed (cap at 25%)", "Strength (infinite)"] },
      { category: "Offense", priority: ["Critical Hit Damage (50 pts)", "Critical Hit Chance (50 pts)", "Attack Speed (situational)", "Cooldown Reduction (IK HotA)"] },
      { category: "Defense", priority: ["Armor (50 pts)", "Life % (50 pts)", "All Resistance (50 pts)"] },
      { category: "Utility", priority: ["Area Damage (50 pts)", "Resource Cost Reduction (50 pts)", "Life on Hit (situational)"] },
    ],
    skillBar: [
      { key: "LMB", abilityName: "Frenzy", rune: "Sidearm", element: "Physical", role: "Primary Generator", note: "Hold LMB on enemies to generate Fury and stack the Frenzy damage buff. Sidearm fires a bonus projectile every third hit for extra AoE." },
      { key: "RMB", abilityName: "Whirlwind", rune: "Blood Funnel", element: "Physical", role: "Main Damage", note: "Hold RMB and move through enemy packs. Never stop spinning — movement applies Rend via Ambo's Pride and maintains the Wastes set bonus." },
      { key: "1", abilityName: "War Cry", rune: "Impunity", element: "None", role: "Defensive Buff", note: "Press 1 at the start of every rift and whenever the buff expires. Impunity adds All Resistances for the whole party." },
      { key: "2", abilityName: "Battle Rage", rune: "Into the Fray", element: "None", role: "Offensive Buff", note: "Press 2 to activate before engaging. Into the Fray generates Fury on every kill, keeping Whirlwind going indefinitely in dense packs." },
      { key: "3", abilityName: "Threatening Shout", rune: "Falter", element: "None", role: "Debuff", note: "Press 3 on elite packs to reduce their damage output by 20%. Falter also reduces their attack speed — essential for surviving high Torment." },
      { key: "4", abilityName: "Wrath of the Berserker", rune: "Striding Giant", element: "None", role: "Ultimate Cooldown", note: "Press 4 before every elite pack and Rift Guardian. Striding Giant provides 50% damage reduction while active. Maintain permanent uptime in IK builds via Obsidian Ring of the Zodiac." },
    ],
    rotation: [
      { step: 1, keys: ["1", "2", "3"], action: "Pre-buff before engaging", detail: "Before entering a pack, press War Cry (1), Battle Rage (2), and Threatening Shout (3) in quick succession. These three buffs must always be active — they multiply your damage and survivability significantly.", timing: "opener" },
      { step: 2, keys: ["4"], action: "Activate Wrath of the Berserker", detail: "Press 4 to pop WotB just before reaching the pack. In IK builds, this should be permanent — the Obsidian Ring of the Zodiac resets its cooldown every time you spend Fury. Never fight elites without it active.", timing: "opener" },
      { step: 3, keys: ["RMB"], action: "Whirlwind through the pack", detail: "Hold RMB and physically move your character through the densest part of the enemy group. Ambo's Pride automatically applies Rend to every enemy you spin through. The Wastes set bonus doubles your damage while spinning — never stop.", timing: "spam" },
      { step: 4, keys: ["LMB"], action: "Frenzy to regenerate Fury", detail: "If Fury drops low and Whirlwind stutters, tap LMB a few times on nearby enemies to regenerate Fury quickly. The Frenzy stacks also increase your damage — try to maintain maximum stacks before re-engaging.", timing: "situational" },
      { step: 5, keys: ["1", "2", "3"], action: "Refresh shouts on cooldown", detail: "All three shouts have cooldowns. Watch their icons and refresh them the moment they expire. Battle Rage's Into the Fray rune generates Fury on kills, so keeping it active is critical during dense packs.", timing: "on-cooldown" },
      { step: 6, keys: ["4"], action: "Maintain WotB uptime", detail: "In IK builds, spending Fury with Whirlwind procs the Obsidian Ring of the Zodiac, resetting WotB's cooldown. Keep spinning to keep WotB permanent. If it drops, immediately press 4 to reactivate before continuing.", timing: "maintain" },
    ],
  },
  {
    id: "crusader",
    name: "Crusader",
    tagline: "Unbending Champion of Faith and Law",
    overview:
      "Crusaders are holy warriors clad in impenetrable plate, wielding massive shields and bone-crunching flails. They are the quintessential tank class, capable of deflecting attacks entirely while unleashing devastating holy magic. Uniquely, they can equip a two-handed weapon in one hand while holding a shield — making them both the most durable and surprisingly one of the most powerful damage dealers in the game.",
    primaryStat: "Strength",
    resource: {
      name: "Wrath",
      description:
        "Wrath regenerates slowly over time and is generated by Primary skills. It powers the Crusader's most devastating holy abilities. Many builds use Cooldown Reduction to maintain permanent uptime on Akarat's Champion rather than managing Wrath directly.",
    },
    color: "#f0c040",
    colorName: "Holy Gold",
    bgGradient: "linear-gradient(135deg, #1a1400 0%, #3d3000 50%, #1a1400 100%)",
    weaponTypes: [
      "Flails (one-handed) — Crusader-exclusive, most powerful legendary affixes",
      "Two-Handed Flails — massive damage, used with Heavenly Strength passive",
      "Crusader Shields — off-hand with Block Chance and unique legendary powers",
      "All standard melee weapons (Swords, Axes, Maces) — less optimal but viable",
    ],
    metaBuilds: [
      {
        name: "Aegis of Valor Fist of the Heavens",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "Smite enemies with holy lightning bolts that chain between targets. Beginner-friendly with high damage output. Excellent for Nephalem Rifts, Bounties, and pushing Greater Rifts.",
        keyItems: ["Aegis of Valor (6-piece)", "Darklight", "Khassett's Cord of Righteousness", "Norvald's Fervor", "Heaven's Fury"],
      },
      {
        name: "Akkhan Condemn",
        tier: "S",
        playstyle: "GR Push",
        description:
          "Commands spectral soldiers while detonating massive holy explosions with Condemn. Maintains permanent Akarat's Champion for near-invincibility and massive damage.",
        keyItems: ["Armor of Akkhan (6-piece)", "Blade of Prophecy", "Unrelenting Phalanx", "Captain Crimson's Trimmings"],
      },
      {
        name: "LoD Bombardment",
        tier: "A",
        playstyle: "GR Push",
        description:
          "Calls down devastating bombardments from the sky using the Belt of the Trove for automation. The Legacy of Dreams gem replaces a set, allowing more flexibility in item choices.",
        keyItems: ["Legacy of Dreams gem", "The Mortal Drama", "Belt of the Trove", "Illusory Boots", "Faithful Memory"],
      },
    ],
    abilities: [
      { name: "Punish", type: "Primary", element: "Holy", keybind: "LMB", keybindNote: "Left Mouse Button — primary skills are always here for constant use while moving.", description: "Strike enemies and gain Hardened Senses, increasing Block Chance. The go-to primary skill for most builds." },
      { name: "Shield Bash", type: "Secondary", element: "Holy", keybind: "RMB", keybindNote: "Right Mouse Button — your main damage skill in shield builds, used constantly.", description: "Charge and bash enemies with your shield, dealing damage based on Block Chance. Core to shield-focused builds." },
      { name: "Fist of the Heavens", type: "Secondary", element: "Lightning", keybind: "RMB", keybindNote: "Right Mouse Button — core damage skill in Aegis of Valor; spam it constantly.", description: "Calls down a bolt of holy lightning that chains between enemies. The centerpiece of the Aegis of Valor build." },
      { name: "Heaven's Fury", type: "Secondary", element: "Fire", keybind: "1", keybindNote: "Slot 1 — pairs with Fist of the Heavens; keep it adjacent on the bar for the Aegis rotation.", description: "Calls down a beam of holy fire from the heavens. Synergizes powerfully with the Aegis of Valor set." },
      { name: "Condemn", type: "Utility", element: "Holy", keybind: "RMB", keybindNote: "Right Mouse Button — spam Condemn constantly in Akkhan builds; needs to be your fastest key.", description: "Builds up a massive holy explosion over 3 seconds. Core to the Akkhan Condemn build with Blade of Prophecy." },
      { name: "Bombardment", type: "Conviction", element: "Fire", keybind: "1", keybindNote: "Slot 1 — used on cooldown; Belt of the Trove auto-fires it, so exact placement is flexible.", description: "Calls in a rain of burning pitch and stone. Automated by Belt of the Trove in the LoD Bombardment build." },
      { name: "Akarat's Champion", type: "Conviction", element: "Holy", keybind: "T", keybindNote: "Bind to T or a mouse thumb button — your most critical cooldown; must be instantly accessible at all times.", description: "Explodes with divine power, massively increasing damage and Wrath regeneration. Maintained permanently in most builds." },
      { name: "Laws of Valor", type: "Laws", element: "None", keybind: "2", keybindNote: "Slot 2 — activated on cooldown for the empowered buff; keep it near your primary attack keys.", description: "Passively increases Attack Speed; active use empowers the effect. Used in most Crusader builds for the damage boost." },
      { name: "Shield Glare", type: "Defensive", element: "Holy", keybind: "3", keybindNote: "Slot 3 — situational crowd control; doesn't need prime placement but should be reachable quickly.", description: "Blinds all enemies in front of you. Used for crowd control and to proc the Blind debuff for certain builds." },
      { name: "Falling Sword", type: "Conviction", element: "Holy", keybind: "4", keybindNote: "Slot 4 — mobility skill used between packs; furthest slot is fine since it's not reaction-critical.", description: "Launch into the heavens and crash down on enemies. Used for mobility and as a damage skill in some builds." },
    ],
    levelingTips: {
      early: [
        "Use Punish as your primary skill — the Retaliate rune adds a free counter-attack.",
        "Equip a shield as soon as possible; Block Chance scales several Crusader skills.",
        "Laws of Valor provides a consistent damage boost — use it from the moment it unlocks.",
        "Sweep Attack is excellent for clearing dense packs early on.",
        "Prioritize Strength and Vitality on gear; Crusaders are naturally tanky but need damage to progress.",
      ],
      mid: [
        "Unlock and use Akarat's Champion — even at low ranks, the damage and Wrath regen are significant.",
        "Start using Condemn or Heaven's Fury as your main damage skill depending on your gear.",
        "The Heavenly Strength passive (level 16) lets you wield a two-handed weapon with a shield — a massive damage boost.",
        "Look for Flails with high damage — they are the Crusader's best-in-slot weapon type.",
        "Equip Iron Skin for emergency survivability in tough situations.",
      ],
      late: [
        "Complete Season Journey chapters II–IV to receive Haedrig's Gift (Aegis of Valor set recommended).",
        "With the Aegis of Valor 2-piece, Fist of the Heavens becomes dramatically more powerful.",
        "Run Master difficulty Bounties to collect Horadric Cache materials for Kanai's Cube recipes.",
        "Use Kanai's Cube to upgrade Rare Flails into Legendaries — the Darklight is your primary target.",
        "Transition to Torment difficulties as soon as your set bonuses are active.",
      ],
      endgame: [
        "Maintain permanent Akarat's Champion uptime — this is the most important mechanical requirement.",
        "In Aegis of Valor, alternate between Fist of the Heavens and Heaven's Fury for maximum synergy.",
        "Cooldown Reduction is the most important secondary stat for most Crusader builds.",
        "Use Norvald's Fervor (Flail + Shield set) to maintain permanent Steed Charge uptime for mobility.",
        "In group play, Crusaders provide Laws buffs — coordinate with your team on which Law to use.",
      ],
    },
    masteryNote:
      "The Crusader's unique ability to equip a two-handed weapon in one hand (via Heavenly Strength) while holding a shield in the other is unmatched in the game. Mastering Cooldown Reduction to maintain permanent Akarat's Champion is the key to unlocking the class's full potential.",
    masteryTips: [
      "Aim for 37–56% Cooldown Reduction to maintain permanent Akarat's Champion uptime.",
      "In Aegis of Valor, the rotation is: cast Fist of the Heavens → Heaven's Fury activates → repeat. Never stop casting.",
      "Blade of Prophecy makes Condemn hit all enemies within 15 yards — position yourself at the center of packs.",
      "Use Illusory Boots in LoD Bombardment to walk through enemies and position Bombardment optimally.",
      "In group play, always use Laws of Valor with the Unstoppable Force rune to reduce skill costs for your team.",
    ],
    paragons: [
      { category: "Core", priority: ["Movement Speed (cap at 25%)", "Strength (infinite)"] },
      { category: "Offense", priority: ["Cooldown Reduction (50 pts — critical)", "Critical Hit Damage (50 pts)", "Critical Hit Chance (50 pts)"] },
      { category: "Defense", priority: ["Armor (50 pts)", "Life % (50 pts)", "All Resistance (50 pts)"] },
      { category: "Utility", priority: ["Area Damage (50 pts)", "Resource Cost Reduction (50 pts)"] },
    ],
    skillBar: [
      { key: "LMB", abilityName: "Punish", rune: "Retaliate", element: "Holy", role: "Primary Generator", note: "Hold LMB to attack and generate Wrath. Retaliate fires a free projectile back at attackers — useful passive damage while you focus on positioning." },
      { key: "RMB", abilityName: "Fist of the Heavens", rune: "Divine Well", element: "Lightning", role: "Main Damage", note: "Spam RMB constantly — this is your primary damage skill in Aegis of Valor builds. Each cast triggers Heaven's Fury via the set bonus. Never stop casting." },
      { key: "1", abilityName: "Heaven's Fury", rune: "Blessed Ground", element: "Fire", role: "AoE Damage", note: "Press 1 to drop a beam of fire on dense packs. In Aegis of Valor, Fist of the Heavens automatically triggers this — but manual casts add extra damage on Rift Guardians." },
      { key: "2", abilityName: "Laws of Valor", rune: "Critical", element: "None", role: "Offensive Buff", note: "Press 2 to activate the empowered Law, granting a 50% Critical Hit Damage bonus for 5 seconds. Use it before every elite pack and Rift Guardian." },
      { key: "3", abilityName: "Iron Skin", rune: "Flash", element: "None", role: "Emergency Defense", note: "Press 3 when taking heavy damage. Flash makes you briefly invincible — use it to survive elite affixes like Arcane Enchanted or Frozen." },
      { key: "4", abilityName: "Akarat's Champion", rune: "Prophet", element: "Holy", role: "Ultimate Cooldown", note: "Press 4 to activate your most important cooldown. Prophet resurrects you once if you die while it's active. Maintain permanent uptime using Cooldown Reduction gear — this is your top stat priority." },
    ],
    rotation: [
      { step: 1, keys: ["4"], action: "Activate Akarat's Champion", detail: "Always open with Akarat's Champion (4). It provides a massive damage boost and the Prophet rune gives you a free resurrection. With enough Cooldown Reduction (37%+), it stays up permanently — never fight without it.", timing: "opener" },
      { step: 2, keys: ["2"], action: "Activate Laws of Valor", detail: "Press 2 to empower your Law. The Critical rune adds 50% Critical Hit Damage for 5 seconds — activate it right before your main damage window for maximum impact.", timing: "opener" },
      { step: 3, keys: ["RMB"], action: "Spam Fist of the Heavens", detail: "Hold RMB and spam Fist of the Heavens as fast as possible. Each cast automatically triggers Heaven's Fury via the Aegis of Valor set bonus. Position yourself in the center of packs so both skills hit the maximum number of enemies.", timing: "spam" },
      { step: 4, keys: ["1"], action: "Drop Heaven's Fury on Rift Guardians", detail: "Against Rift Guardians and tough elites, manually press 1 to add an extra Heaven's Fury beam on top of the set-triggered ones. Stack all beams on the same target for maximum single-target damage.", timing: "situational" },
      { step: 5, keys: ["3"], action: "Iron Skin on dangerous affixes", detail: "When you see Arcane Enchanted beams, Frozen orbs, or Jailer chains, immediately press 3 to activate Iron Skin. Flash makes you invincible for 1 second — enough to escape most lethal situations.", timing: "situational" },
      { step: 6, keys: ["2", "4"], action: "Refresh buffs on cooldown", detail: "Watch your buff timers. Reactivate Laws of Valor (2) every 5 seconds for the empowered bonus, and ensure Akarat's Champion (4) never drops. With proper CDR, both should be near-permanent.", timing: "maintain" },
    ],
  },
  {
    id: "demon-hunter",
    name: "Demon Hunter",
    tagline: "Relentless Pursuer of the Darkness",
    overview:
      "Demon Hunters are ranged specialists who combine crossbows, magical devices, and traps to hunt the demons that destroyed their lives. They utilize a unique dual-resource system — Hatred for offense and Discipline for defense — requiring constant resource management. Masters of mobility, they are always moving, always repositioning, and always dealing damage from a safe distance.",
    primaryStat: "Dexterity",
    resource: {
      name: "Hatred / Discipline",
      description:
        "Hatred is the primary offensive resource, regenerating passively and through Primary skills. Discipline is the secondary defensive resource, regenerating very slowly and used for movement and utility skills. Managing both simultaneously is the defining challenge of the Demon Hunter.",
    },
    color: "#8e44ad",
    colorName: "Shadow Violet",
    bgGradient: "linear-gradient(135deg, #0d0014 0%, #1e0033 50%, #0d0014 100%)",
    weaponTypes: [
      "Hand Crossbows — one-handed, can dual-wield for attack speed; many build-defining legendaries",
      "Crossbows — two-handed, highest damage per shot",
      "Bows — two-handed, balanced attack speed and damage",
      "Quivers — off-hand item with Attack Speed and skill bonuses",
    ],
    metaBuilds: [
      {
        name: "Gears of Dreadlands Hungering Arrow",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "An extremely mobile build using Strafe to automatically fire Hungering Arrow projectiles. Easy to play with a high skill ceiling. The Ninth Cirri Satchel makes arrows pierce and bounce, multiplying damage exponentially.",
        keyItems: ["Gears of Dreadlands (6-piece)", "The Ninth Cirri Satchel", "Hunter's Wrath", "Depth Diggers", "Odyssey's End"],
      },
      {
        name: "Shadow Impale",
        tier: "S",
        playstyle: "GR Push",
        description:
          "A melee-range assassin build that uses Impale for massive single-target and AoE burst damage. Requires getting close to enemies, making positioning and Smoke Screen timing critical.",
        keyItems: ["The Shadow's Mantle (6-piece)", "Karlei's Point", "Holy Point Shot", "Elusive Ring", "Dawn"],
      },
      {
        name: "Embodiment of the Marauder Sentry",
        tier: "A",
        playstyle: "GR Push",
        description:
          "Places Sentries that fire Cluster Arrow or Multishot, dealing massive AoE damage. A slower, more strategic playstyle that rewards good positioning and cooldown management.",
        keyItems: ["Embodiment of the Marauder (6-piece)", "Zoey's Secret", "The Cloak of Garwulf", "Dawn", "Hellcat Waistguard"],
      },
    ],
    abilities: [
      { name: "Hungering Arrow", type: "Primary", element: "Physical", keybind: "LMB", keybindNote: "Left Mouse Button — primary skills always go here; in GoD builds you rarely click this manually.", description: "Fires a seeking arrow that pierces through enemies. The core skill of the GoD build — The Ninth Cirri Satchel makes it bounce between targets." },
      { name: "Impale", type: "Hatred Spender", element: "Physical", keybind: "RMB", keybindNote: "Right Mouse Button — your primary damage skill in Shadow builds; spam it constantly.", description: "Throws a massive knife dealing devastating single-target damage. The core skill of the Shadow Impale build." },
      { name: "Multishot", type: "Hatred Spender", element: "Physical", keybind: "RMB", keybindNote: "Right Mouse Button — main AoE damage skill; needs to be your fastest key for constant use.", description: "Fires a massive volley of arrows hitting all enemies in a wide arc. Excellent AoE damage for speedfarming." },
      { name: "Cluster Arrow", type: "Hatred Spender", element: "Fire", description: "Fires an explosive cluster that deals massive AoE damage. The primary skill in Marauder Sentry builds.", keybind: "RMB", keybindNote: "Right Mouse Button — your main damage output in Marauder builds; needs instant access." },
      { name: "Strafe", type: "Hatred Spender", element: "Physical", keybind: "RMB", keybindNote: "Right Mouse Button — in GoD builds, hold RMB to strafe continuously; this is your primary action.", description: "Continuously fires arrows while moving. In GoD builds, this automatically fires Hungering Arrows via the set bonus." },
      { name: "Vault", type: "Discipline", element: "None", keybind: "Space", keybindNote: "Spacebar or mouse thumb button — your primary survival tool; must be instantly accessible without looking down.", description: "Tumbles to a new location, providing brief immunity during animation. The primary mobility skill — use it constantly." },
      { name: "Smoke Screen", type: "Discipline", element: "None", keybind: "1", keybindNote: "Slot 1 — emergency invincibility; keep it on your most accessible number key for instant reaction.", description: "Vanishes in a cloud of smoke, becoming invincible for its duration. Critical for surviving in Shadow Impale builds." },
      { name: "Vengeance", type: "Archery", element: "Cold", keybind: "T", keybindNote: "Bind to T or a mouse thumb button — your most important cooldown; must be instantly accessible at all times.", description: "Transforms into a demonic form, granting crowd-control immunity and 40% multiplicative damage. Maintained permanently with Dawn." },
      { name: "Preparation", type: "Discipline", element: "None", keybind: "3", keybindNote: "Slot 3 — used when Discipline is critically low; doesn't need prime placement but must be reachable.", description: "Restores Discipline. Used with Focused Mind or Invigoration runes to maintain Discipline for Vault and Smoke Screen." },
      { name: "Sentry", type: "Devices", element: "Physical", keybind: "2", keybindNote: "Slot 2 — place Sentries constantly in Marauder builds; keep it accessible since you place them every few seconds.", description: "Places a turret that fires Hatred Spenders. The core mechanic of Marauder builds — each Sentry activates the set bonus." },
    ],
    levelingTips: {
      early: [
        "Use Hungering Arrow as your primary skill — it seeks enemies automatically, making it forgiving for beginners.",
        "Equip Vault immediately when it unlocks — mobility is your primary survival tool.",
        "Use Caltrops and Spike Trap for area denial while you reposition.",
        "Multishot is excellent for clearing dense packs of weak enemies.",
        "Prioritize Dexterity on all gear — it directly increases your damage output.",
      ],
      mid: [
        "Unlock Vengeance and use it on cooldown — even without Dawn, the damage boost is significant.",
        "Start managing your dual resources consciously: save Discipline for emergencies, spend Hatred freely.",
        "Companion (Bat) provides Hatred regeneration — use it to sustain longer fights.",
        "Look for Hand Crossbows with high damage and attack speed for the fastest leveling.",
        "Use Preparation with the Punishment rune to convert Discipline into Hatred when needed.",
      ],
      late: [
        "Complete Season Journey chapters to receive Haedrig's Gift — GoD or Shadow's Mantle are both excellent.",
        "Dawn (Hand Crossbow) is your most important legendary — it reduces Vengeance cooldown by 65%, enabling permanent uptime.",
        "Use Kanai's Cube to upgrade Rare Hand Crossbows targeting Dawn and Karlei's Point.",
        "The Elusive Ring (Shadow Impale) provides massive damage reduction while Smoke Screen is active.",
        "Transition to Torment VI once you have your 4-piece set bonus active.",
      ],
      endgame: [
        "In GoD builds, always keep Strafe active — stopping breaks the momentum buff from the set.",
        "Maintain permanent Vengeance uptime using Dawn in Kanai's Cube or equipped.",
        "Stack Critical Hit Chance, Critical Hit Damage, and Elemental Damage on gear.",
        "In Shadow Impale, use Smoke Screen aggressively — it resets Impale's cooldown via Karlei's Point.",
        "For Marauder Sentry, place Sentries at choke points and let them do the work while you maintain Vengeance.",
      ],
    },
    masteryNote:
      "The Demon Hunter's dual-resource system is deceptively deep. Discipline is precious — wasting it on unnecessary Vaults when Smoke Screen would be more efficient is a common mistake. True mastery means never running out of either resource at a critical moment.",
    masteryTips: [
      "In GoD, the Momentum buff from Strafe stacks up to 15 times — never stop moving or you lose your damage.",
      "Shadow Impale requires getting within melee range — use Smoke Screen offensively, not just defensively.",
      "Odyssey's End (Marauder) makes enemies take 60% more damage when Entangled — always apply it before Sentries fire.",
      "Use Preparation with the Punishment rune as an emergency Hatred dump when Discipline is full.",
      "In group play, Demon Hunters provide the highest single-target damage — focus on Rift Guardians and elites.",
    ],
    paragons: [
      { category: "Core", priority: ["Movement Speed (cap at 25%)", "Dexterity (infinite)"] },
      { category: "Offense", priority: ["Critical Hit Damage (50 pts)", "Critical Hit Chance (50 pts)", "Attack Speed (GoD builds)", "Cooldown Reduction (Vengeance uptime)"] },
      { category: "Defense", priority: ["Life % (50 pts)", "Armor (50 pts)", "All Resistance (50 pts)"] },
      { category: "Utility", priority: ["Area Damage (50 pts)", "Resource Cost Reduction (50 pts)"] },
    ],
    skillBar: [
      { key: "LMB", abilityName: "Hungering Arrow", rune: "Devouring Arrow", element: "Physical", role: "Primary Generator", note: "In GoD builds, LMB is rarely clicked manually — Strafe fires Hungering Arrows automatically. Use it only to start combat or when Strafe is on cooldown." },
      { key: "RMB", abilityName: "Strafe", rune: "Drifting Shadow", element: "Physical", role: "Main Damage / Movement", note: "Hold RMB to channel Strafe. This is your entire playstyle in GoD — moving while strafing fires Hungering Arrows and builds the Momentum buff. Never stop moving." },
      { key: "1", abilityName: "Smoke Screen", rune: "Displacement", element: "None", role: "Emergency Escape", note: "Press 1 the instant you are in danger — Frozen, Jailer, or Arcane Enchanted. Displacement teleports you a short distance while invincible. Your most important survival key." },
      { key: "2", abilityName: "Preparation", rune: "Focused Mind", element: "None", role: "Discipline Recovery", note: "Press 2 when Discipline is low and you need Smoke Screen or Vault available. Focused Mind regenerates Discipline over 15 seconds — use it proactively, not reactively." },
      { key: "3", abilityName: "Companion", rune: "Wolf Companion", element: "None", role: "Damage Buff", note: "Press 3 to activate the Wolf Companion's howl, granting 30% increased damage for 10 seconds. Use it before every elite pack and Rift Guardian for maximum burst." },
      { key: "4", abilityName: "Vengeance", rune: "Dark Heart", element: "Cold", role: "Ultimate Cooldown", note: "Press 4 to enter Vengeance form — 40% multiplicative damage increase and crowd control immunity. With Dawn in Kanai's Cube, this is permanent. Never let it drop." },
    ],
    rotation: [
      { step: 1, keys: ["4"], action: "Activate Vengeance", detail: "Always open with Vengeance (4). It provides a 40% multiplicative damage boost and makes you immune to crowd control. With Dawn reducing its cooldown by 65%, you should maintain permanent uptime — if it ever drops, reactivate immediately.", timing: "opener" },
      { step: 2, keys: ["3"], action: "Activate Wolf Companion", detail: "Press 3 to trigger the Wolf's howl for a 30% damage buff. Use this before every elite pack. It has a 30-second cooldown, so time it carefully for maximum uptime on tough targets.", timing: "opener" },
      { step: 3, keys: ["RMB"], action: "Strafe through the pack", detail: "Hold RMB and move constantly. Strafing fires Hungering Arrows automatically via the GoD set bonus, and each arrow builds Momentum stacks (up to 15). More stacks = more damage. Moving in a figure-eight pattern keeps you in range while maximizing arrow output.", timing: "spam" },
      { step: 4, keys: ["1"], action: "Smoke Screen on dangerous affixes", detail: "The moment you see a dangerous elite affix activating — Frozen orbs forming, Arcane beams sweeping, Jailer chains — immediately press 1. Displacement teleports you out of harm's way while invincible. Reaction time is everything here.", timing: "situational" },
      { step: 5, keys: ["2"], action: "Preparation when Discipline is low", detail: "Discipline regenerates slowly. If you have used Smoke Screen and Vault multiple times, press 2 to start Focused Mind's regeneration. Don't wait until you are completely empty — manage it proactively.", timing: "on-cooldown" },
      { step: 6, keys: ["4", "3"], action: "Maintain buff uptime", detail: "Keep Vengeance (4) and Wolf Companion (3) active at all times. Check their icons constantly. Vengeance should never drop with Dawn equipped. Wolf Companion has a 30-second cooldown — refresh it on every significant fight.", timing: "maintain" },
    ],
  },
  {
    id: "monk",
    name: "Monk",
    tagline: "Sacred Warrior of the Seven-Sided Path",
    overview:
      "Monks are sacred warriors who channel divine power through sheer force of will. Masters of hand-to-hand combat, they possess unparalleled mobility — darting in and out of melees with healing waves, protective mantras, and holy-empowered attacks. Their speed and versatility make them excellent both as damage dealers and as support characters in group play.",
    primaryStat: "Dexterity",
    resource: {
      name: "Spirit",
      description:
        "Spirit does not regenerate automatically — it is generated by Primary skills, completing attack combos, and specific items. Many Monk builds invest heavily in Spirit generation through skills like Epiphany or Resource Cost Reduction items to sustain their Spirit spenders.",
    },
    color: "#e67e22",
    colorName: "Sacred Amber",
    bgGradient: "linear-gradient(135deg, #1a0d00 0%, #3d2000 50%, #1a0d00 100%)",
    weaponTypes: [
      "Fist Weapons — Monk-exclusive, fastest attack speed, many build-defining legendaries",
      "Daibos — two-handed Monk-exclusive, high damage with unique legendary affixes",
      "One-handed Melee Weapons (Swords, Axes, Maces) — less optimal but viable",
      "Shields — usable but rarely optimal; most builds prefer dual-wield or Daibo",
    ],
    metaBuilds: [
      {
        name: "Inna Mystic Ally",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "Buffs Mystic Allies to deal devastating damage. The Fire variant excels in Greater Rifts while the Cold variant dominates T16 speedfarming. Relies on pet AI but is extremely powerful.",
        keyItems: ["Inna's Mantra (6-piece)", "The Crudest Boots", "Bindings of the Lesser Gods", "Lefebvre's Soliloquy"],
      },
      {
        name: "Sunwuko Tempest Rush",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "Channels Tempest Rush through enemy packs, triggering massive Sweeping Wind explosions. Extremely fun and mobile with strong damage output for both solo and group content.",
        keyItems: ["Monkey King's Garb (6-piece)", "Won Khim Lau", "Balance", "Cesar's Memento", "Kyoshiro's Soul"],
      },
      {
        name: "LoD Wave of Light",
        tier: "A",
        playstyle: "GR Push",
        description:
          "Drops massive bells on enemies using Wave of Light, amplified by numerous damage multipliers. The Legacy of Dreams gem replaces a set, allowing flexible item combinations.",
        keyItems: ["Legacy of Dreams gem", "Incense Torch of the Grand Temple", "Kyoshiro's Blade", "Pinto's Pride", "Tzo-Krin's Gaze"],
      },
    ],
    abilities: [
      { name: "Fists of Thunder", type: "Primary", element: "Lightning", keybind: "LMB", keybindNote: "Left Mouse Button — primary skill for Spirit generation; click to teleport to enemies and attack.", description: "Teleports to targets and unleashes fast punches. Every third hit deals increased damage. Generates Spirit rapidly with the Quickening rune." },
      { name: "Tempest Rush", type: "Spirit Spender", element: "Fire", keybind: "RMB", keybindNote: "Right Mouse Button — hold RMB to channel Tempest Rush continuously; this is your entire playstyle in Sunwuko.", description: "Channels a rushing tornado through enemies. The core skill of the Sunwuko build — never stop moving." },
      { name: "Wave of Light", type: "Spirit Spender", element: "Fire", keybind: "RMB", keybindNote: "Right Mouse Button — your primary damage skill; spam it on every pack.", description: "Drops a massive bell on enemies dealing heavy AoE damage. The core skill of the LoD WoL build." },
      { name: "Lashing Tail Kick", type: "Spirit Spender", element: "Physical", keybind: "RMB", keybindNote: "Right Mouse Button — main damage skill in speedfarming builds; needs constant use.", description: "A powerful roundhouse kick dealing AoE damage. Used in several speedfarming builds." },
      { name: "Dashing Strike", type: "Technique", element: "Physical", keybind: "Space", keybindNote: "Spacebar or mouse thumb button — your primary mobility skill; must be instantly accessible for constant repositioning.", description: "Quickly dashes up to 50 yards. Has multiple charges and is the primary mobility skill for all Monk builds." },
      { name: "Exploding Palm", type: "Technique", element: "Physical", keybind: "1", keybindNote: "Slot 1 — apply to enemies before detonating; keep it accessible for the setup phase of your rotation.", description: "Applies a bleed; if the enemy dies while bleeding, it explodes for massive AoE damage. Core to group play Monk builds." },
      { name: "Sweeping Wind", type: "Technique", element: "Fire", keybind: "2", keybindNote: "Slot 2 — maintained passively; activate to refresh stacks. Keep it near your primary keys.", description: "Surrounds the Monk in a damage vortex. Refreshed by melee attacks and stacks for increased damage in Sunwuko builds." },
      { name: "Cyclone Strike", type: "Focus", element: "Holy", keybind: "3", keybindNote: "Slot 3 — used to pull enemies together before AoE; situational but important in group play.", description: "Pulls nearby enemies toward the Monk and blasts them. Excellent for grouping enemies for AoE damage." },
      { name: "Epiphany", type: "Focus", element: "Fire", keybind: "T", keybindNote: "Bind to T or mouse thumb — critical resource management cooldown; must be instantly accessible at all times.", description: "Increases Spirit regeneration and allows melee attacks to instantly dash to targets. Critical for resource management." },
      { name: "Inner Sanctuary", type: "Defensive", element: "Holy", keybind: "4", keybindNote: "Slot 4 — place on cooldown in dangerous situations; furthest slot is acceptable since it's not reaction-based.", description: "Creates a protective circle reducing damage taken. Essential for the support Monk role in group play." },
    ],
    levelingTips: {
      early: [
        "Use Exploding Palm for AoE damage — trigger explosions with Sweeping Wind or Lashing Tail Kick.",
        "Fists of Thunder is your best primary skill for Spirit generation, especially with the Quickening rune.",
        "Dashing Strike unlocks at level 9 — use it constantly for mobility and engaging packs.",
        "Mantra of Salvation provides early protection; switch to Mantra of Healing for Spirit regeneration later.",
        "Gamble Blood Shards on Boots (The Crudest Boots) and Bracers (Gungdo Gear) for powerful early legendaries.",
      ],
      mid: [
        "Integrate Sweeping Wind with the Inner Storm rune for sustained AoE and Spirit regeneration.",
        "Unlock the Harmony passive at level 45 — it converts a single resistance to All Resistance, dramatically improving toughness.",
        "Epiphany is a game-changer for Spirit management — use it on cooldown.",
        "Look for Fist Weapons and Daibos with high damage and Dexterity.",
        "Cyclone Strike is excellent for grouping enemies before your AoE skills detonate them.",
      ],
      late: [
        "Complete Season Journey chapters II–IV for Haedrig's Gift (Inna's Mantra is the typical season reward).",
        "With Inna's 2-piece, Mystic Allies become significantly stronger — start building around them.",
        "The Crudest Boots doubles your Mystic Ally count — this is your most important item.",
        "Use Kanai's Cube to upgrade Rare Fist Weapons targeting build-specific legendaries.",
        "Transition to Torment VI once your 4-piece set bonus is active.",
      ],
      endgame: [
        "In Tempest Rush builds, never stop channeling — the Sunwuko set bonus requires constant movement.",
        "Epiphany with the Desert Shroud rune provides 50% damage reduction — use it on cooldown.",
        "In group play, Monks provide Inner Sanctuary and Cyclone Strike for crowd control and grouping.",
        "Bindings of the Lesser Gods (Mystic Ally builds) doubles damage when enemies are in a Cyclone Strike vortex.",
        "Wave of Light builds require precise positioning — drop bells directly on elite packs for maximum damage.",
      ],
    },
    masteryNote:
      "The Monk's unparalleled mobility is their greatest asset. True mastery means never standing still — constantly dashing between packs, pulling enemies together with Cyclone Strike, and maintaining all buffs simultaneously while dealing damage.",
    masteryTips: [
      "In Tempest Rush, the Cesar's Memento bracers require you to hit enemies with a different skill first — always open with Dashing Strike.",
      "Exploding Palm's explosion radius is massive — in group play, one detonation can clear an entire screen.",
      "The Crudest Boots doubles Mystic Ally count — position them strategically around elite packs.",
      "Epiphany's Desert Shroud rune provides 50% damage reduction — never let it drop off.",
      "In Wave of Light, the Incense Torch of the Grand Temple reduces cost by 75% — stack Resource Cost Reduction for near-free casts.",
    ],
    paragons: [
      { category: "Core", priority: ["Movement Speed (cap at 25%)", "Dexterity (infinite)"] },
      { category: "Offense", priority: ["Critical Hit Damage (50 pts)", "Critical Hit Chance (50 pts)", "Cooldown Reduction (Epiphany)", "Attack Speed (situational)"] },
      { category: "Defense", priority: ["Armor (50 pts)", "Life % (50 pts)", "All Resistance (50 pts)"] },
      { category: "Utility", priority: ["Area Damage (50 pts)", "Resource Cost Reduction (50 pts)"] },
    ],
    skillBar: [
      { key: "LMB", abilityName: "Fists of Thunder", rune: "Quickening", element: "Lightning", role: "Primary Generator", note: "Click LMB to teleport to enemies and generate Spirit rapidly. Quickening generates extra Spirit on every hit — essential for fueling Tempest Rush or Wave of Light." },
      { key: "RMB", abilityName: "Tempest Rush", rune: "Flurry", element: "Fire", role: "Main Damage / Movement", note: "Hold RMB and move through packs continuously. Flurry leaves behind a damaging tornado on every enemy you pass through. The Sunwuko set multiplies this damage — never stop channeling." },
      { key: "1", abilityName: "Dashing Strike", rune: "Blinding Speed", element: "Physical", role: "Mobility / Opener", note: "Press 1 to dash to a target before engaging with Tempest Rush. Cesar's Memento bracers require you to hit enemies with a different skill first — always open each pack with Dashing Strike before switching to RMB." },
      { key: "2", abilityName: "Sweeping Wind", rune: "Inner Storm", element: "Fire", role: "Damage Aura", note: "Press 2 to activate your damage vortex. Inner Storm generates Spirit while the vortex is active, helping sustain Tempest Rush. Refresh it whenever the stack count drops — maximum stacks triple the damage." },
      { key: "3", abilityName: "Mantra of Salvation", rune: "Agility", element: "None", role: "Defensive Buff", note: "Press 3 to activate the mantra's empowered effect for 3 seconds. Use it reactively when facing dangerous elite affixes or taking heavy damage. Agility adds dodge chance passively." },
      { key: "4", abilityName: "Epiphany", rune: "Desert Shroud", element: "Fire", role: "Ultimate Cooldown", note: "Press 4 on cooldown — never let it drop. Desert Shroud provides 50% damage reduction, making you nearly unkillable. It also allows melee attacks to instantly teleport to targets, supercharging your mobility." },
    ],
    rotation: [
      { step: 1, keys: ["4"], action: "Activate Epiphany", detail: "Open every fight with Epiphany (4). Desert Shroud's 50% damage reduction is your primary survival tool. It also enables instant teleportation to enemies, making your Tempest Rush flow seamlessly between targets.", timing: "opener" },
      { step: 2, keys: ["2"], action: "Activate Sweeping Wind", detail: "Press 2 to start your damage vortex. Build it to maximum stacks immediately by attacking a few enemies with Fists of Thunder before engaging the main pack. Inner Storm will then generate Spirit passively.", timing: "opener" },
      { step: 3, keys: ["1"], action: "Dashing Strike into the pack", detail: "Press 1 to dash into the center of the enemy group. This is mandatory if you have Cesar's Memento equipped — it applies a debuff that multiplies your Tempest Rush damage. Always dash before switching to RMB.", timing: "opener" },
      { step: 4, keys: ["RMB"], action: "Channel Tempest Rush through enemies", detail: "Hold RMB and physically move your character through the densest part of the pack. Flurry leaves damaging tornadoes on every enemy you pass. Move in tight circles to hit the same enemies multiple times and maximize the Sunwuko set bonus.", timing: "spam" },
      { step: 5, keys: ["LMB"], action: "Fists of Thunder to regenerate Spirit", detail: "If Spirit drops and Tempest Rush stutters, tap LMB a few times to regenerate Spirit quickly via Quickening. Sweeping Wind's Inner Storm also generates Spirit passively — keep it active to minimize interruptions.", timing: "situational" },
      { step: 6, keys: ["4", "2", "3"], action: "Refresh all cooldowns on schedule", detail: "Epiphany (4) should be permanent with enough CDR. Sweeping Wind (2) refreshes automatically from attacks but check the stack count. Mantra of Salvation (3) should be activated reactively when you take burst damage.", timing: "maintain" },
    ],
  },
  {
    id: "necromancer",
    name: "Necromancer",
    tagline: "Custodian of the Balance Between Life and Death",
    overview:
      "Necromancers are masters of dark arts, commanding hordes of the dead, crushing enemies with bone and blood spells, and debilitating foes with curses. They are strategic commanders who control the battlefield through grim will and calculated use of life and death magic. Uniquely, they can sacrifice their own health to power their most devastating abilities.",
    primaryStat: "Intelligence",
    resource: {
      name: "Essence",
      description:
        "Essence is capped at 200 and does not regenerate passively — it is generated by hitting enemies with Primary skills. Unlike other resources, Essence does not decay over time, allowing for careful accumulation before unleashing powerful spenders.",
    },
    color: "#27ae60",
    colorName: "Bone Green",
    bgGradient: "linear-gradient(135deg, #001a08 0%, #003d15 50%, #001a08 100%)",
    weaponTypes: [
      "Scythes (one-handed) — Necromancer-exclusive, most powerful legendary affixes",
      "Two-Handed Scythes — massive damage, often used with Phylactery off-hand",
      "Phylacteries — off-hand item with unique Necromancer-specific legendary powers",
      "Shields — usable but rarely optimal for damage builds",
    ],
    metaBuilds: [
      {
        name: "Masquerade Bone Spear",
        tier: "S",
        playstyle: "GR Push",
        description:
          "Fires devastating bone spears amplified by Simulacrums (mirror images). Fast-paced with tremendous AoE damage. Requires precise positioning to maximize the piercing projectile's impact.",
        keyItems: ["Masquerade of the Burning Carnival (6-piece)", "Gelmindor's Marrow Guards", "Briggs' Wrath", "Simulacrum"],
      },
      {
        name: "LoD Death Nova",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "Unleashes explosive Death Novas that obliterate screens of enemies. Excellent AoE but struggles with single targets. The Legacy of Dreams gem provides the damage multiplier.",
        keyItems: ["Legacy of Dreams gem", "Funerary Pick", "Iron Rose", "Bloodtide Blade", "Nemesis Bracers"],
      },
      {
        name: "Trag'Oul Death Nova",
        tier: "A",
        playstyle: "GR Push",
        description:
          "Similar to LoD Death Nova but with increased survivability from the Trag'Oul set bonuses. Strong AoE damage with better sustain, ideal for players learning the Death Nova playstyle.",
        keyItems: ["Trag'Oul's Avatar (6-piece)", "Funerary Pick", "Iron Rose", "Bloodtide Blade"],
      },
    ],
    abilities: [
      { name: "Bone Spikes", type: "Primary", element: "Physical", keybind: "LMB", keybindNote: "Left Mouse Button — primary Essence generator; click constantly to fuel your spenders.", description: "Summons bone spikes from the ground dealing Physical damage and generating Essence. The standard primary skill for most builds." },
      { name: "Grim Scythe", type: "Primary", element: "Physical", keybind: "LMB", keybindNote: "Left Mouse Button — sweeping primary attack; use in melee range to hit multiple enemies and generate Essence quickly.", description: "Slashes with a summoned scythe in front of you. Hits multiple enemies and generates significant Essence per hit." },
      { name: "Bone Spear", type: "Secondary", element: "Physical", keybind: "RMB", keybindNote: "Right Mouse Button — your main damage skill in Masquerade; aim carefully to pierce through packs.", description: "Fires a piercing projectile through all enemies in a line. The core skill of the Masquerade build — Simulacrums multiply its damage." },
      { name: "Death Nova", type: "Secondary", element: "Poison", keybind: "RMB", keybindNote: "Right Mouse Button — spam this constantly in Death Nova builds; you need to be surrounded by enemies.", description: "Unleashes a nova of necrotic energy damaging all nearby enemies. The core skill of both LoD and Trag'Oul Death Nova builds." },
      { name: "Corpse Explosion", type: "Corpses", element: "Physical", keybind: "1", keybindNote: "Slot 1 — spam during Land of the Dead windows; keep it on your most accessible number key.", description: "Detonates up to 5 corpses simultaneously, dealing massive AoE damage. Requires corpses — use Simulacrum or Bone Armor to generate them." },
      { name: "Command Skeletons", type: "Reanimation", element: "Physical", keybind: "2", keybindNote: "Slot 2 — used to redirect skeletons to focus targets; click it then click the target.", description: "Passively raises skeletons and commands them to focus targets. The core skill of summoner builds." },
      { name: "Skeletal Mage", type: "Secondary", element: "Physical", keybind: "2", keybindNote: "Slot 2 — summon on cooldown; keep it accessible since you cast it frequently.", description: "Raises a powerful skeletal mage that attacks enemies. Used in Rathma and LoD summoner builds." },
      { name: "Bone Armor", type: "Blood & Bone", element: "Physical", keybind: "3", keybindNote: "Slot 3 — use on cooldown for damage reduction and corpse generation; doesn't need prime placement.", description: "Rips bones from nearby enemies to create protective armor. Provides damage reduction and generates corpses for Corpse Explosion." },
      { name: "Blood Rush", type: "Blood & Bone", element: "Physical", keybind: "Space", keybindNote: "Spacebar or mouse thumb — your only mobility skill; must be instantly accessible for emergency escapes.", description: "Teleports up to 50 yards by shedding mortal flesh. The primary mobility skill — costs a percentage of maximum Life." },
      { name: "Land of the Dead", type: "Reanimation", element: "Physical", keybind: "T", keybindNote: "Bind to T or mouse thumb — your ultimate burst cooldown; must be instantly accessible to maximize the 5-second window.", description: "Raises a massive army from the dead for 5 seconds, enabling unlimited Corpse skills. The ultimate cooldown for burst damage." },
    ],
    levelingTips: {
      early: [
        "Use Corpse Explosion for efficient mob clearing — it deals massive AoE damage when corpses are available.",
        "Bone Spikes is your primary Essence generator — use it to fuel your spenders.",
        "Command Skeletons provides free damage and acts as a distraction for enemies.",
        "Prioritize Intelligence and Vitality on gear for damage and survivability.",
        "Blood Rush is your escape tool — always keep it available for emergencies.",
      ],
      mid: [
        "Experiment with Bone Spear as your primary damage skill — it pierces through multiple enemies.",
        "Simulacrum (unlocks at level 50) is a game-changer — it mirrors your skills for massive damage multiplication.",
        "Start looking for Scythes with high damage and Intelligence for maximum output.",
        "Bone Armor provides significant damage reduction — use it on cooldown.",
        "Land of the Dead enables burst damage windows — save it for elite packs and Rift Guardians.",
      ],
      late: [
        "Complete Season Journey chapters II–IV for Haedrig's Gift (Masquerade or Trag'Oul are common season rewards).",
        "Gelmindor's Marrow Guards (Masquerade) makes Simulacrum Bone Spears deal 300% more damage — your top priority item.",
        "Use Kanai's Cube to upgrade Rare Scythes targeting Funerary Pick or Briggs' Wrath.",
        "Transition to Torment VI once your 4-piece set bonus is active.",
        "Nemesis Bracers are universally useful — equip them or extract the power via Kanai's Cube.",
      ],
      endgame: [
        "In Masquerade Bone Spear, position yourself so Bone Spears pierce through as many enemies as possible.",
        "Land of the Dead is your burst window — save Essence and cooldowns for when it's active.",
        "Corpse generation is critical — Bone Armor and Simulacrum both generate corpses for Corpse Explosion.",
        "In Death Nova builds, stay in the center of enemy packs — the nova hits all surrounding enemies.",
        "Stack Intelligence, Critical Hit Chance, and Critical Hit Damage on all gear pieces.",
      ],
    },
    masteryNote:
      "The Necromancer's unique mechanic is corpse management. Corpses can be consumed for Essence, exploded for AoE damage, or raised as minions. Mastering when to generate, save, and spend corpses is what separates a good Necromancer from a great one.",
    masteryTips: [
      "In Masquerade Bone Spear, Simulacrums cast their own Bone Spears — position yourself so all three pierce the same pack.",
      "Land of the Dead enables unlimited Corpse Explosion — pre-stack Essence before activating it for maximum burst.",
      "Briggs' Wrath pulls enemies to you when you cast Bone Spear — use it to group enemies before your AoE.",
      "Bone Armor generates a corpse for each enemy hit — use it in dense packs to fuel Corpse Explosion.",
      "In group play, Necromancers provide Frailty (Aura of Frailty) for a 15% damage amplification to all enemies.",
    ],
    paragons: [
      { category: "Core", priority: ["Movement Speed (cap at 25%)", "Intelligence (infinite)"] },
      { category: "Offense", priority: ["Critical Hit Damage (50 pts)", "Critical Hit Chance (50 pts)", "Cooldown Reduction (Land of the Dead)", "Attack Speed (situational)"] },
      { category: "Defense", priority: ["Armor (50 pts)", "Life % (50 pts)", "All Resistance (50 pts)"] },
      { category: "Utility", priority: ["Area Damage (50 pts)", "Resource Cost Reduction (50 pts)"] },
    ],
    skillBar: [
      { key: "LMB", abilityName: "Grim Scythe", rune: "Cursed Scythe", element: "Physical", role: "Primary Generator", note: "Swing LMB to hit multiple enemies and generate Essence. Cursed Scythe has a 15% chance to apply a random curse on every hit — free debuffs that amplify your damage." },
      { key: "RMB", abilityName: "Bone Spear", rune: "Teeth", element: "Physical", role: "Main Damage", note: "Aim RMB through lines of enemies so the spear pierces as many targets as possible. In Masquerade builds, your Simulacrums fire their own Bone Spears simultaneously — stack all three on the same pack." },
      { key: "1", abilityName: "Corpse Explosion", rune: "Close to the Bone", element: "Physical", role: "AoE Burst", note: "Spam 1 during Land of the Dead windows when unlimited corpses are available. Close to the Bone reduces the cost to zero — press it as fast as possible during your burst window." },
      { key: "2", abilityName: "Bone Armor", rune: "Dislocation", element: "Physical", role: "Defense / Corpse Gen", note: "Press 2 on cooldown in dense packs. Dislocation stuns nearby enemies and generates a corpse for each enemy hit — fueling your Corpse Explosion spam." },
      { key: "3", abilityName: "Blood Rush", rune: "Potency", element: "Physical", role: "Mobility / Escape", note: "Press 3 to teleport out of danger. Potency briefly increases your armor after teleporting. This is your only mobility skill — use it for repositioning and escaping lethal affixes." },
      { key: "4", abilityName: "Land of the Dead", rune: "Frozen Lands", element: "Physical", role: "Ultimate Burst Cooldown", note: "Press 4 to open your burst window. For 5 seconds, unlimited corpses are available. Pre-stack Essence before pressing 4, then immediately spam Corpse Explosion (1) as fast as possible." },
    ],
    rotation: [
      { step: 1, keys: ["LMB"], action: "Generate Essence with Grim Scythe", detail: "Before engaging a large pack, swing LMB several times to build up Essence toward the 200 cap. Cursed Scythe will apply random curses, softening enemies before your burst.", timing: "opener" },
      { step: 2, keys: ["2"], action: "Bone Armor to generate corpses", detail: "Press 2 in the middle of the pack to stun enemies and generate corpses. These corpses are what fuel your Corpse Explosion spam. Dislocation also gives you a brief window of safety.", timing: "opener" },
      { step: 3, keys: ["RMB"], action: "Bone Spear to position and damage", detail: "Fire Bone Spear through the pack to deal damage and position yourself. With Briggs' Wrath equipped, Bone Spear pulls enemies toward you — group them tightly before your burst window.", timing: "spam" },
      { step: 4, keys: ["4"], action: "Activate Land of the Dead", detail: "Press 4 when surrounded by a large pack with full Essence. This is your most important cooldown — the 5-second window of unlimited corpses is when nearly all your damage happens. Save it for the biggest packs.", timing: "on-cooldown" },
      { step: 5, keys: ["1"], action: "Spam Corpse Explosion during LotD", detail: "During Land of the Dead, press 1 as fast as humanly possible. Every press detonates multiple corpses for massive AoE damage. Close to the Bone makes it free — your only limit is click speed.", timing: "spam" },
      { step: 6, keys: ["3"], action: "Blood Rush to reposition safely", detail: "After your burst window, use Blood Rush (3) to teleport away from dangerous affixes or reposition for the next pack. Potency's armor bonus helps you survive the brief moment between packs.", timing: "situational" },
    ],
  },
  {
    id: "witch-doctor",
    name: "Witch Doctor",
    tagline: "Voice of the Spirits, Master of the Undying",
    overview:
      "Witch Doctors are spiritual warriors who summon dead souls and crawling creatures to do their bidding. They control the battlefield with hexes, curses, and pets, assaulting enemies with various elemental attacks. Their playstyle revolves around outsmarting foes, rendering them helpless, and letting their summoned allies or devastating curses finish them off.",
    primaryStat: "Intelligence",
    resource: {
      name: "Mana",
      description:
        "Mana is a vast but slowly-regenerating resource. Witch Doctors must manage it carefully, relying on summoned creatures and free Primary attacks to conserve it while their powerful spells recharge. Several builds invest in Mana regeneration or use free-cost skills to avoid depletion.",
    },
    color: "#16a085",
    colorName: "Voodoo Teal",
    bgGradient: "linear-gradient(135deg, #001a14 0%, #003d2a 50%, #001a14 100%)",
    weaponTypes: [
      "Ceremonial Knives — Witch Doctor-exclusive, most build-defining legendary affixes (Sacred Harvester, The Barber, Voo's Juicer)",
      "Staves — several important staves like Wormwood, Staff of Chiroptera, and SuWong Diviner",
      "Mojos — off-hand item with unique Witch Doctor-specific legendary powers",
      "One-handed Swords, Axes, Maces — less optimal but viable with the right legendary affixes",
    ],
    metaBuilds: [
      {
        name: "Mundunugu Spirit Barrage",
        tier: "S",
        playstyle: "GR Push",
        description:
          "Focuses on releasing massive AoE Spirit Barrage bursts, dominating solo Greater Rift pushing. The Mundunugu set amplifies Spirit Barrage damage based on the number of enemies hit.",
        keyItems: ["Mundunugu's Regalia (6-piece)", "The Barber", "Gazing Demise", "Ring of Emptiness"],
      },
      {
        name: "Jade Harvester Haunt",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "Applies Haunt and Locust Swarm DoTs to enemies, then instantly converts all accumulated damage into burst damage with Soul Harvest. Extremely satisfying and powerful.",
        keyItems: ["Raiment of the Jade Harvester (6-piece)", "Ring of Emptiness", "Quetzalcoatl", "Sacred Harvester"],
      },
      {
        name: "Arachyr Corpse Spiders",
        tier: "A",
        playstyle: "Speedfarm / GR Push",
        description:
          "Spreads Corpse Spiders damage to all enemies infested by the Arachyr set. The Angry Chicken variant (Hex: Angry Chicken) is exceptional for speed farming due to its explosive mobility.",
        keyItems: ["Spirit of Arachyr (6-piece)", "The Spider Queen's Grasp", "Manajuma's Way", "Cluckeye"],
      },
    ],
    abilities: [
      { name: "Poison Dart", type: "Primary", element: "Poison", keybind: "LMB", keybindNote: "Left Mouse Button — primary Mana generator; click constantly to fund your spenders.", description: "Fires a deadly dart dealing Poison damage over time. The standard primary skill for Mana generation." },
      { name: "Spirit Barrage", type: "Mana Spender", element: "Physical", keybind: "RMB", keybindNote: "Right Mouse Button — your primary damage skill in Mundunugu; spam it into packs and let The Barber detonate.", description: "Unleashes a barrage of spirit bolts. The core skill of the Mundunugu build — The Barber stores damage for a massive delayed explosion." },
      { name: "Haunt", type: "Mana Spender", element: "Cold", keybind: "RMB", keybindNote: "Right Mouse Button — in Jade Harvester, apply this to every enemy constantly; it's your most-used skill.", description: "Haunts an enemy with a spirit that deals Cold damage over time. Core to the Jade Harvester build — apply to all enemies before Soul Harvest." },
      { name: "Locust Swarm", type: "Mana Spender", element: "Poison", keybind: "1", keybindNote: "Slot 1 — apply to one enemy and let it spread; keep it accessible for the Jade Harvester DoT setup rotation.", description: "Unleashes a plague of locusts that spreads between enemies. Pairs with Haunt in Jade Harvester builds for maximum DoT stacking." },
      { name: "Soul Harvest", type: "Terror", element: "Physical", keybind: "2", keybindNote: "Slot 2 — your burst trigger in Jade Harvester; keep it close to your DoT keys for a fast rotation.", description: "Feeds on the life force of nearby enemies, gaining Intelligence. In Jade Harvester, instantly converts all DoT damage into burst damage." },
      { name: "Corpse Spiders", type: "Secondary", element: "Physical", keybind: "RMB", keybindNote: "Right Mouse Button — spam jar throws constantly in Arachyr builds; needs to be your fastest key.", description: "Throws a jar of spiders that attack nearby enemies. The core skill of the Arachyr build — The Spider Queen's Grasp amplifies their damage." },
      { name: "Gargantuan", type: "Voodoo", element: "Physical", keybind: "4", keybindNote: "Slot 4 — summoned once and maintained; doesn't need prime placement since you cast it infrequently.", description: "Summons a massive zombie to fight for you. Used in summoner builds and as a damage boost in several meta builds." },
      { name: "Spirit Walk", type: "Defensive", element: "None", keybind: "Space", keybindNote: "Spacebar or mouse thumb — your primary survival tool; must be instantly accessible without looking down.", description: "Leaves the physical body to enter the spirit realm, becoming invincible and moving freely. The primary survival skill." },
      { name: "Hex", type: "Utility", element: "None", keybind: "3", keybindNote: "Slot 3 — in Angry Chicken builds, this is your mobility skill; keep it accessible for constant use between packs.", description: "Transforms enemies into harmless chickens. The Angry Chicken rune transforms the Witch Doctor for explosive mobility in the Arachyr build." },
      { name: "Piranhas", type: "Decay", element: "Poison", keybind: "T", keybindNote: "Bind to T — apply before every elite pack for the 15% damage amplification; needs to be quickly accessible.", description: "Summons a pool of piranhas dealing Poison damage and increasing damage taken by affected enemies by 15%." },
    ],
    levelingTips: {
      early: [
        "Focus on summoning skills — Summon Zombie Dogs and Gargantuan provide free damage and act as meat shields.",
        "Use Haunt and Acid Cloud for supplementary damage while your pets do the heavy lifting.",
        "Spirit Walk is your primary survival tool — use it to escape dangerous situations.",
        "Unlock Spirit Vessel (level 30) — it provides a free death every 60 seconds, dramatically improving survivability.",
        "Fetish Sycophants (level 30) passively summons Fetishes when you cast spells — a significant free damage boost.",
      ],
      mid: [
        "Incorporate Fierce Loyalty (level 45) and Grave Injustice (level 50) passives for pet buffs.",
        "Switch Spirit Walk to the Severance rune at level 47 for faster movement during Spirit Walk.",
        "Soul Harvest provides a significant Intelligence buff — use it on cooldown near enemy packs.",
        "Look for Ceremonial Knives with high damage and Intelligence for maximum output.",
        "Piranhas provides a 15% damage amplification — apply it to all elite packs before spending Mana.",
      ],
      late: [
        "Complete Season Journey chapters II–IV for Haedrig's Gift (Jade Harvester or Mundunugu are common rewards).",
        "The Ring of Emptiness doubles damage against enemies affected by Haunt or Locust Swarm — your top priority item.",
        "Use Kanai's Cube to upgrade Rare Ceremonial Knives targeting Sacred Harvester or The Barber.",
        "Transition to Torment VI once your 4-piece set bonus is active.",
        "Quetzalcoatl doubles Soul Harvest damage — equip it or extract its power via Kanai's Cube.",
      ],
      endgame: [
        "In Jade Harvester, apply Haunt and Locust Swarm to all enemies before Soul Harvesting for maximum burst.",
        "Ring of Emptiness requires enemies to be affected by both Haunt AND Locust Swarm for the full 200% bonus.",
        "In Mundunugu, The Barber stores Spirit Barrage damage for 2 seconds then releases it all at once — position carefully.",
        "Spirit Walk is your emergency escape — never waste it on trivial situations.",
        "In Arachyr Angry Chicken, use Hex: Angry Chicken to travel between packs at extreme speed, then detonate on arrival.",
      ],
    },
    masteryNote:
      "The Jade Harvester build's DoT-to-burst mechanic is one of the most unique in the game. Mastering the rhythm of applying Haunt and Locust Swarm to entire screens of enemies before triggering Soul Harvest for an instant kill is deeply satisfying and highly effective.",
    masteryTips: [
      "In Jade Harvester, the Sacred Harvester increases Soul Harvest stacks to 10 — always maintain maximum stacks.",
      "Ring of Emptiness requires BOTH Haunt and Locust Swarm on the target — apply both before spending Mana.",
      "In Arachyr Angry Chicken, the explosion radius is massive — detonate in the center of the largest pack.",
      "Piranhas with the Piranhado rune pulls enemies together — use it before any AoE skill for maximum efficiency.",
      "In group play, Witch Doctors provide Piranhas for grouping and Ring of Emptiness for a team-wide damage amplification.",
    ],
    paragons: [
      { category: "Core", priority: ["Movement Speed (cap at 25%)", "Intelligence (infinite)"] },
      { category: "Offense", priority: ["Critical Hit Damage (50 pts)", "Critical Hit Chance (50 pts)", "Cooldown Reduction (Soul Harvest)", "Attack Speed (situational)"] },
      { category: "Defense", priority: ["Armor (50 pts)", "Life % (50 pts)", "All Resistance (50 pts)"] },
      { category: "Utility", priority: ["Area Damage (50 pts)", "Resource Cost Reduction (50 pts)"] },
    ],
    skillBar: [
      { key: "LMB", abilityName: "Poison Dart", rune: "Splinters", element: "Poison", role: "Primary Generator", note: "Click LMB to generate Mana and apply Poison damage. Splinters fires three darts at once, hitting multiple enemies. Use this when Mana is low to refuel before spending on bigger skills." },
      { key: "RMB", abilityName: "Haunt", rune: "Resentful Spirits", element: "Cold", role: "DoT Application", note: "Click RMB on every enemy in the pack to apply Haunt. Resentful Spirits lets Haunt jump to nearby enemies automatically. This is your primary setup skill in Jade Harvester — every enemy must be Haunted before you Soul Harvest." },
      { key: "1", abilityName: "Locust Swarm", rune: "Pestilence", element: "Poison", role: "DoT Spread", note: "Press 1 on one enemy and let Pestilence spread the swarm to the entire pack automatically. Both Haunt AND Locust Swarm must be on every enemy for Ring of Emptiness to grant the full 200% damage bonus." },
      { key: "2", abilityName: "Soul Harvest", rune: "Languish", element: "Physical", role: "Burst Trigger", note: "Press 2 when all enemies are Haunted and Swarmed. In Jade Harvester, this instantly converts all accumulated DoT damage into a single burst. Languish also slows enemies, keeping them in range." },
      { key: "3", abilityName: "Spirit Walk", rune: "Jaunt", element: "None", role: "Emergency Escape", note: "Press 3 the instant you are in serious danger. Jaunt extends the duration to 3 seconds and increases movement speed. This is your only invincibility skill — never waste it on trivial repositioning." },
      { key: "4", abilityName: "Piranhas", rune: "Piranhado", element: "Poison", role: "Crowd Control / Debuff", note: "Press 4 before every elite pack. Piranhado pulls all nearby enemies into a tight cluster and increases their damage taken by 15%. Always use this before applying your DoTs for maximum efficiency." },
    ],
    rotation: [
      { step: 1, keys: ["4"], action: "Piranhas to group and debuff enemies", detail: "Open every elite pack with Piranhas (4). Piranhado pulls all enemies into a tight cluster and applies a 15% damage amplification. With enemies grouped, your DoTs will spread faster and your Soul Harvest will hit more targets.", timing: "opener" },
      { step: 2, keys: ["1"], action: "Apply Locust Swarm to one enemy", detail: "Press 1 on a single enemy in the center of the pack. Pestilence spreads the swarm automatically to all nearby enemies. Wait a moment to confirm the spread before moving to the next step.", timing: "opener" },
      { step: 3, keys: ["RMB"], action: "Haunt every enemy in the pack", detail: "Click RMB on each enemy to apply Haunt. Resentful Spirits helps it jump between targets, but manually clicking ensures full coverage. Both Haunt and Locust Swarm must be active on every target for Ring of Emptiness to work.", timing: "spam" },
      { step: 4, keys: ["2"], action: "Soul Harvest for instant burst", detail: "Once all enemies have both DoTs active, press 2. Jade Harvester instantly converts all accumulated DoT damage into a single explosive burst. The more DoT stacks on each enemy, the bigger the explosion.", timing: "on-cooldown" },
      { step: 5, keys: ["LMB"], action: "Poison Dart to regenerate Mana", detail: "After spending Mana on Haunt and Locust Swarm, click LMB a few times to regenerate. Splinters hits multiple enemies at once, making Mana recovery fast in dense packs.", timing: "situational" },
      { step: 6, keys: ["3"], action: "Spirit Walk for emergency escape", detail: "If you are about to die — Frozen, Jailer, or overwhelmed by damage — press 3 immediately. Jaunt gives you 3 seconds of invincibility and increased movement speed. Save it for genuine emergencies only.", timing: "situational" },
    ],
  },
  {
    id: "wizard",
    name: "Wizard",
    tagline: "Renegade Arcanist of Unlimited Power",
    overview:
      "Wizards are renegade arcanists who manipulate the raw forces of fire, ice, lightning, and arcane energy to obliterate their enemies. Masters of elemental destruction, they can freeze time, teleport across the battlefield, and unleash cataclysmic spells. Their fast-regenerating Arcane Power means they are rarely resource-starved, allowing them to maintain a constant barrage of devastating magic.",
    primaryStat: "Intelligence",
    resource: {
      name: "Arcane Power",
      description:
        "Arcane Power regenerates quickly on its own, making Wizards one of the least resource-constrained classes. It is generated by Primary skills and regenerates passively at a rate of 20 per second. Most builds have minimal resource management concerns.",
    },
    color: "#2980b9",
    colorName: "Arcane Blue",
    bgGradient: "linear-gradient(135deg, #000d1a 0%, #001f3d 50%, #000d1a 100%)",
    weaponTypes: [
      "Wands — Wizard-exclusive, fastest attack speed, many build-defining legendary affixes",
      "Swords, Daggers — one-handed options for dual-wield or off-hand combinations",
      "Two-Handed Staves — high damage, often with powerful legendary affixes",
      "Sources (off-hand) — Wizard-exclusive off-hand with unique legendary powers",
    ],
    metaBuilds: [
      {
        name: "Firebird Mirror Image",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "Ignites enemies with fire damage that spreads infinitely between burning targets. Mirror Images multiply the Firebird ignition stacks. One of the strongest builds in the game for both farming and pushing.",
        keyItems: ["Firebird's Finery (6-piece)", "Deathwish", "Etched Sigil", "Mirror Image", "Aquila Cuirass"],
      },
      {
        name: "Typhon Hydra",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "Summons powerful Hydras that deal continuous fire damage. The Typhon set dramatically amplifies Hydra damage while reducing their cooldown. A strong and relatively straightforward build.",
        keyItems: ["Typhon's Veil (6-piece)", "Serpent's Sparker", "The Magistrate", "Etched Sigil"],
      },
      {
        name: "LoD Frozen Orb",
        tier: "A",
        playstyle: "Speedfarm / GR Push",
        description:
          "Launches massive Frozen Orbs that shatter on impact, dealing heavy cold damage to all nearby enemies. The Legacy of Dreams gem provides the damage multiplier without requiring a full set.",
        keyItems: ["Legacy of Dreams gem", "Halo of Karini", "The Oculus", "Manald Heal", "Triumvirate"],
      },
    ],
    abilities: [
      { name: "Magic Missile", type: "Primary", element: "Arcane", keybind: "LMB", keybindNote: "Left Mouse Button — primary skill for Arcane Power generation; click to fire seeking missiles.", description: "Fires a seeking missile of arcane energy. The standard primary skill for Arcane Power generation." },
      { name: "Electrocute", type: "Primary", element: "Lightning", keybind: "LMB", keybindNote: "Left Mouse Button — hold to channel lightning chains across multiple enemies; great for Arcane Power generation.", description: "Channels a beam of lightning that chains between nearby enemies. Excellent for generating Arcane Power against multiple targets." },
      { name: "Hydra", type: "Arcane Power Spender", element: "Fire", keybind: "RMB", keybindNote: "Right Mouse Button — place Hydras constantly in Typhon builds; needs to be your fastest key.", description: "Summons a multi-headed hydra that breathes fire. The core skill of the Typhon build — Serpent's Sparker allows two Hydras simultaneously." },
      { name: "Frozen Orb", type: "Arcane Power Spender", element: "Cold", keybind: "RMB", keybindNote: "Right Mouse Button — your primary damage skill; fire into packs and let the ice shards spread.", description: "Launches a massive orb that explodes in a shower of ice shards. The core skill of the LoD Frozen Orb build." },
      { name: "Arcane Torrent", type: "Arcane Power Spender", element: "Arcane", keybind: "RMB", keybindNote: "Right Mouse Button — hold to channel continuously in Etched Sigil builds; never release the button.", description: "Channels a barrage of arcane bolts. Used in Etched Sigil builds to automatically cast other skills." },
      { name: "Disintegrate", type: "Arcane Power Spender", element: "Arcane", keybind: "RMB", keybindNote: "Right Mouse Button — hold to channel the beam; aim carefully to hit as many enemies as possible.", description: "Channels a beam of pure arcane energy that disintegrates everything in its path." },
      { name: "Teleport", type: "Utility", element: "Arcane", keybind: "Space", keybindNote: "Spacebar or mouse thumb — your primary mobility skill; must be instantly accessible for constant repositioning and escapes.", description: "Instantly teleports to a target location. The primary mobility skill — use it constantly for repositioning." },
      { name: "Mirror Image", type: "Conjuration", element: "None", keybind: "T", keybindNote: "Bind to T — recast constantly in Firebird builds; images die quickly so you need fast access to resummon them.", description: "Creates mirror images that mimic your attacks. In Firebird builds, they generate ignition stacks independently." },
      { name: "Slow Time", type: "Utility", element: "Arcane", keybind: "3", keybindNote: "Slot 3 — place on Rift Guardians and elite packs; situational but important for crowd control.", description: "Creates a bubble that slows time for enemies inside. Used for crowd control and to proc the Delsere's Magnum Opus set bonus." },
      { name: "Black Hole", type: "Arcane Power Spender", element: "Arcane", keybind: "1", keybindNote: "Slot 1 — use before AoE damage to group enemies; keep it accessible for the setup phase of your rotation.", description: "Creates a singularity that pulls enemies together. Excellent for grouping enemies before AoE damage." },
    ],
    levelingTips: {
      early: [
        "Use Magic Missile or Electrocute as your primary skill for consistent Arcane Power generation.",
        "Teleport is your primary mobility skill — use it to escape dangerous situations and reposition.",
        "Arcane Torrent or Disintegrate are excellent channeled damage skills for early leveling.",
        "Frost Nova provides crowd control — freeze enemies before unleashing AoE damage.",
        "Prioritize Intelligence on all gear for maximum damage output.",
      ],
      mid: [
        "Unlock and use Hydra — even without the Typhon set, it provides significant passive damage.",
        "Mirror Image provides both offensive and defensive value — use it on cooldown.",
        "Black Hole is excellent for grouping enemies before your AoE skills detonate them.",
        "Look for Wands and Sources with high damage and Intelligence.",
        "Slow Time provides crowd control and can proc several powerful set bonuses.",
      ],
      late: [
        "Complete Season Journey chapters II–IV for Haedrig's Gift (Firebird's Finery or Typhon's Veil are common rewards).",
        "Etched Sigil (Source) automatically casts your secondary skill while channeling — your top priority item.",
        "Use Kanai's Cube to upgrade Rare Wands targeting Deathwish or Serpent's Sparker.",
        "Transition to Torment VI once your 4-piece set bonus is active.",
        "Deathwish increases damage by 325% while channeling — equip it or extract its power via Kanai's Cube.",
      ],
      endgame: [
        "In Firebird Mirror Image, maintain Mirror Images on cooldown — they independently generate ignition stacks.",
        "In Typhon Hydra, always have two Hydras active — Serpent's Sparker enables this.",
        "Stack Cold Damage on gear for Frozen Orb builds — elemental damage is a direct multiplier.",
        "The Oculus ring creates a zone that increases damage by 85% — always stand in it.",
        "In group play, Wizards provide Slow Time for crowd control and The Oculus ring buff for the entire team.",
      ],
    },
    masteryNote:
      "The Wizard's mastery lies in maximizing uptime on damage multipliers. Deathwish's 325% channeling bonus, Mirror Image's independent ignition stacks, and The Oculus ring's 85% damage zone must all be active simultaneously for peak performance.",
    masteryTips: [
      "In Firebird, Mirror Images die quickly — recast them constantly to maintain ignition stack generation.",
      "The Oculus ring creates a random damage zone — always reposition to stand in it when it appears.",
      "In Typhon Hydra, Etched Sigil automatically casts Hydra while you channel Arcane Torrent — never stop channeling.",
      "Deathwish requires channeling — Arcane Torrent or Disintegrate must be active for the 325% bonus.",
      "In group play, cast Slow Time on Rift Guardians — it provides a significant damage window for your team.",
    ],
    paragons: [
      { category: "Core", priority: ["Movement Speed (cap at 25%)", "Intelligence (infinite)"] },
      { category: "Offense", priority: ["Critical Hit Damage (50 pts)", "Critical Hit Chance (50 pts)", "Cooldown Reduction (Mirror Image)", "Attack Speed (situational)"] },
      { category: "Defense", priority: ["Armor (50 pts)", "Life % (50 pts)", "All Resistance (50 pts)"] },
      { category: "Utility", priority: ["Area Damage (50 pts)", "Resource Cost Reduction (50 pts)"] },
    ],
    skillBar: [
      { key: "LMB", abilityName: "Magic Missile", rune: "Seeker", element: "Arcane", role: "Primary Generator", note: "Click LMB to generate Arcane Power and deal minor damage. Seeker homes in on enemies automatically. In channeling builds, you rarely use this — Arcane Power regenerates passively fast enough." },
      { key: "RMB", abilityName: "Arcane Torrent", rune: "Static Discharge", element: "Arcane", role: "Main Channel / Damage", note: "Hold RMB to channel continuously. Etched Sigil automatically casts your secondary skill (Hydra or Frozen Orb) while you channel. Never release RMB during a fight — Deathwish's 325% damage bonus requires constant channeling." },
      { key: "1", abilityName: "Hydra", rune: "Mammoth Hydra", element: "Fire", role: "Persistent Damage", note: "Press 1 to place a Hydra at the target location. Mammoth Hydra breathes a massive cone of fire. In Typhon builds, Etched Sigil casts this automatically while you channel — but manual placement on Rift Guardians adds extra damage." },
      { key: "2", abilityName: "Mirror Image", rune: "Duplicates", element: "None", role: "Damage Multiplier / Defense", note: "Press 2 on cooldown. In Firebird builds, Mirror Images independently generate ignition stacks, multiplying your damage. They also draw enemy attention away from you. Recast immediately when they die." },
      { key: "3", abilityName: "Teleport", rune: "Safe Passage", element: "Arcane", role: "Mobility / Defense", note: "Press 3 to blink to a new location. Safe Passage reduces damage taken for 5 seconds after teleporting. Use it to escape dangerous affixes and reposition between packs." },
      { key: "4", abilityName: "Black Hole", rune: "Supermassive", element: "Arcane", role: "Crowd Control / Setup", note: "Press 4 to pull all nearby enemies into a tight cluster before your AoE damage. Supermassive increases the pull radius. Always use this before channeling Arcane Torrent so all enemies are stacked for maximum Area Damage." },
    ],
    rotation: [
      { step: 1, keys: ["4"], action: "Black Hole to group enemies", detail: "Open every pack with Black Hole (4). Supermassive pulls all enemies into a tight cluster. This is critical for Area Damage — stacked enemies multiply your effective damage exponentially. Never skip this step on large packs.", timing: "opener" },
      { step: 2, keys: ["2"], action: "Summon Mirror Images", detail: "Press 2 to spawn Mirror Images immediately. In Firebird builds they generate ignition stacks independently, effectively tripling your damage output. In Typhon builds they serve as decoys. Recast them the moment they die.", timing: "opener" },
      { step: 3, keys: ["1"], action: "Place Hydra on the pack", detail: "Press 1 to drop a Mammoth Hydra directly on the clustered enemies. Position it at the center of the group so the fire cone hits as many targets as possible. In Typhon builds, Etched Sigil handles this automatically while you channel.", timing: "opener" },
      { step: 4, keys: ["RMB"], action: "Channel Arcane Torrent", detail: "Hold RMB and never release it during the fight. Deathwish grants 325% increased damage while channeling — this is your most important multiplier. Etched Sigil fires Hydra automatically while you channel. Stay in The Oculus ring zone whenever it appears.", timing: "spam" },
      { step: 5, keys: ["3"], action: "Teleport to escape or reposition", detail: "When dangerous affixes activate — Arcane beams, Frozen orbs, or Waller — press 3 to blink away. Safe Passage gives you 5 seconds of damage reduction after teleporting. Return to channeling immediately after repositioning.", timing: "situational" },
      { step: 6, keys: ["2", "1"], action: "Refresh Mirror Images and Hydra", detail: "Mirror Images die quickly — recast them (2) every few seconds. Replace your Hydra (1) when it expires or when you move to a new location. Keeping both active is essential for sustained damage output.", timing: "maintain" },
    ],
  },
];

export const classMap: Record<string, ClassData> = Object.fromEntries(
  classes.map((c) => [c.id, c])
);
