// Sanctuary Grimoire Design System
// Each class has a unique color theme applied site-wide when selected

export interface MetaBuild {
  name: string;
  description: string;
  keyItems: string[];
  tier: "S" | "A" | "B";
  playstyle: string;
}

export interface Ability {
  name: string;
  description: string;
  type: string;
  element?: string;
}

export interface LevelingTips {
  early: string[];   // 1-30
  mid: string[];     // 31-60
  late: string[];    // 61-70
  endgame: string[]; // 70+
}

export interface ClassData {
  id: string;
  name: string;
  tagline: string;
  overview: string;
  primaryStat: string;
  resource: { name: string; description: string };
  color: string;       // Tailwind-compatible hex for accent
  colorName: string;   // Human-readable color name
  bgGradient: string;  // CSS gradient for hero
  weaponTypes: string[];
  metaBuilds: MetaBuild[];
  abilities: Ability[];
  levelingTips: LevelingTips;
  masteryNote: string;
  masteryTips: string[];
  paragons: { category: string; priority: string[] }[];
}

export const classes: ClassData[] = [
  {
    id: "barbarian",
    name: "Barbarian",
    tagline: "Savage Wanderer of the Steppes",
    overview:
      "Barbarians are savage wanderers who excel in close-quarters combat, utilizing mighty ground stomps, leaping attacks, and dual-wielded slashes to decimate foes. They are ruthless brawlers who build up Fury through combat to unleash massive, sweeping strikes. While they have strong solo pushing builds, Barbarians are often essential support in group play due to their monstrous pulling abilities.",
    primaryStat: "Strength",
    resource: {
      name: "Fury",
      description:
        "Fury is generated by dealing and taking damage, as well as through Primary skills. It depletes slowly outside of combat. Key skills like War Cry, Threatening Shout, and Furious Charge help maintain Fury during intense fights.",
    },
    color: "#c0392b",
    colorName: "Volcanic Red",
    bgGradient: "linear-gradient(135deg, #1a0505 0%, #3d0a0a 50%, #1a0505 100%)",
    weaponTypes: [
      "Mighty Weapons (one-handed and two-handed) — Barbarian-exclusive, often with powerful legendary affixes",
      "Swords, Axes, Maces, Spears, Polearms",
      "Can dual-wield any two one-handed weapons",
      "Can equip shields for defensive builds",
    ],
    metaBuilds: [
      {
        name: "Wrath of the Wastes WW/Rend",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "The iconic Whirlwind Barbarian. Spin through enemy packs applying Rend's devastating bleed while the Wrath of the Wastes set amplifies every rotation. One of the most satisfying builds in the game.",
        keyItems: ["Wrath of the Wastes (6-piece)", "Ambo's Pride", "Lamentation", "Mortick's Brace", "Bul-Kathos's Oath"],
      },
      {
        name: "Immortal King's HotA",
        tier: "S",
        playstyle: "GR Push",
        description:
          "Maintains permanent Wrath of the Berserker and Call of the Ancients uptime, then unleashes devastating Hammer of the Ancients strikes. A cornerstone build for solo pushing.",
        keyItems: ["Immortal King's Call (6-piece)", "Bracers of the First Men", "The Gavel of Judgment", "Mortick's Brace", "Fury of the Ancients"],
      },
      {
        name: "Might of the Earth Leapquake",
        tier: "A",
        playstyle: "GR Push / Fun",
        description:
          "Leap repeatedly to trigger Earthquakes, then use Ground Stomp to reset Leap's cooldown. Lut Socks is the key item that makes this loop possible. Extremely satisfying to play.",
        keyItems: ["Might of the Earth (6-piece)", "Lut Socks", "Blade of the Tribes", "Girdle of Giants", "Seismic Slam"],
      },
    ],
    abilities: [
      { name: "Frenzy", type: "Primary", element: "Physical", description: "Rapidly attacks enemies, generating Fury and stacking a damage buff with each hit. Core to several high-tier builds." },
      { name: "Whirlwind", type: "Fury Spender", element: "Physical", description: "Spin through enemy packs dealing continuous damage. The centerpiece of the WW/Rend build." },
      { name: "Hammer of the Ancients", type: "Fury Spender", element: "Physical", description: "Calls down a massive hammer dealing heavy area damage. The core skill of the IK HotA build." },
      { name: "Rend", type: "Fury Spender", element: "Physical", description: "Causes enemies to bleed for massive damage over time. Applied automatically by Ambo's Pride while Whirlwinding." },
      { name: "Leap", type: "Technique", element: "Physical", description: "Jump to a location, slamming the ground. With Lut Socks, generates up to 3 charges and triggers Earthquakes." },
      { name: "Earthquake", type: "Technique", element: "Fire", description: "Creates a massive tremor dealing fire damage. The core damage skill of the Leapquake build." },
      { name: "Furious Charge", type: "Technique", element: "Physical", description: "Charge through enemies dealing damage. Used for mobility, Fury generation, and as a damage skill in the Raekor build." },
      { name: "War Cry", type: "Shout", element: "None", description: "Provides significant Armor and Fury. Almost universally used across all Barbarian builds for its defensive value." },
      { name: "Threatening Shout", type: "Shout", element: "None", description: "Reduces enemy damage dealt. Used in support (zBarb) builds and some solo builds for toughness." },
      { name: "Wrath of the Berserker", type: "Warcry", element: "None", description: "Massive offensive buff providing increased attack speed, crit chance, and dodge. Maintained permanently in IK builds." },
      { name: "Ancient Spear", type: "Technique", element: "Physical", description: "Throws a spear to pull enemies. The Rage Flip rune is essential for the support Barbarian (zBarb) role in group play." },
      { name: "Call of the Ancients", type: "Warcry", element: "Physical", description: "Summons three ancient warriors to fight alongside you. Required for the IK set bonus activation." },
    ],
    levelingTips: {
      early: [
        "Use Cleave or Frenzy as your primary skill for consistent Fury generation and damage.",
        "Equip War Cry early — the Impunity rune provides All Resistances, dramatically improving survivability.",
        "Prioritize two-handed weapons for raw damage; the higher damage range makes leveling faster.",
        "Ignore Vitality on gear — Strength provides Armor, and your natural toughness is sufficient early on.",
        "Use Ignore Pain with the Iron Hide rune when things get tough — it's a lifesaver in dense packs.",
      ],
      mid: [
        "Unlock and use Whirlwind once you have enough Fury generation to sustain it.",
        "Start looking for Mighty Weapons — they have Barbarian-specific legendary affixes that are build-defining.",
        "Equip Battle Rage for a consistent damage boost; the Marauder's Rage rune is excellent.",
        "Begin using Furious Charge for mobility between packs — it dramatically speeds up leveling.",
        "Look for items with Strength, Critical Hit Chance, and Critical Hit Damage as secondary priorities.",
      ],
      late: [
        "Focus on completing the Season Journey chapters to earn Haedrig's Gift (a free 6-piece set).",
        "Run Nephalem Rifts on the highest Torment you can clear in under 5 minutes for efficient gear drops.",
        "Use Kanai's Cube to upgrade Rare Mighty Weapons into Legendaries — the item pool is small and targeted.",
        "Prioritize getting your 2-piece and 4-piece set bonuses before pushing to Torment VI+.",
        "Start gambling Blood Shards at Kadala for Bracers and Belts — these slots have strong build-enabling legendaries.",
      ],
      endgame: [
        "Allocate Paragon points: Movement Speed cap first, then Main Stat (Strength) for damage.",
        "In the Offense category, prioritize Critical Hit Damage, then Critical Hit Chance.",
        "Area Damage is crucial for group play and dense pack situations — stack it on gear.",
        "For WW/Rend, maintain permanent Rend uptime — Ambo's Pride applies it automatically while spinning.",
        "The zBarb support role in 4-player groups requires mastering Ancient Spear Rage Flip for pixel-pulling.",
        "Push Greater Rifts by fishing for favorable maps (Battlefield of Eternity, Festering Woods) and elite-dense layouts.",
      ],
    },
    masteryNote:
      "The support Barbarian (zBarb) is one of the most skill-intensive roles in the game. Mastering Ancient Spear Rage Flip to pixel-pull monster packs into tight clusters for your damage dealers is an art form that separates good players from great ones.",
    masteryTips: [
      "Learn to 'pixel-pull' — use Ancient Spear Rage Flip to drag monsters into a single pixel for maximum Area Damage.",
      "In WW/Rend, never stop spinning — movement generates Rend stacks and maintains the Wastes set bonus.",
      "For IK HotA, use Furious Charge to reset Wrath of the Berserker cooldown via the Obsidian Ring of the Zodiac.",
      "Manage Fury carefully in HotA builds — spending Fury with Hammer of the Ancients while maintaining WotB uptime is the core loop.",
      "In Leapquake, always have 3 Leap charges ready before engaging a large elite pack for maximum burst damage.",
    ],
    paragons: [
      { category: "Core", priority: ["Movement Speed (cap at 25%)", "Strength (infinite)"] },
      { category: "Offense", priority: ["Critical Hit Damage (50 pts)", "Critical Hit Chance (50 pts)", "Attack Speed (situational)", "Cooldown Reduction (IK HotA)"] },
      { category: "Defense", priority: ["Armor (50 pts)", "Life % (50 pts)", "All Resistance (50 pts)"] },
      { category: "Utility", priority: ["Area Damage (50 pts)", "Resource Cost Reduction (50 pts)", "Life on Hit (situational)"] },
    ],
  },
  {
    id: "crusader",
    name: "Crusader",
    tagline: "Unbending Champion of Faith and Law",
    overview:
      "Crusaders are holy warriors clad in impenetrable plate, wielding massive shields and bone-crunching flails. They are the quintessential tank class, capable of deflecting attacks entirely while unleashing devastating holy magic. Uniquely, they can equip a two-handed weapon in one hand while holding a shield — making them both the most durable and surprisingly one of the most powerful damage dealers in the game.",
    primaryStat: "Strength",
    resource: {
      name: "Wrath",
      description:
        "Wrath regenerates slowly over time and is generated by Primary skills. It powers the Crusader's most devastating holy abilities. Many builds use Cooldown Reduction to maintain permanent uptime on Akarat's Champion rather than managing Wrath directly.",
    },
    color: "#f0c040",
    colorName: "Holy Gold",
    bgGradient: "linear-gradient(135deg, #1a1400 0%, #3d3000 50%, #1a1400 100%)",
    weaponTypes: [
      "Flails (one-handed) — Crusader-exclusive, most powerful legendary affixes",
      "Two-Handed Flails — massive damage, used with Heavenly Strength passive",
      "Crusader Shields — off-hand with Block Chance and unique legendary powers",
      "All standard melee weapons (Swords, Axes, Maces) — less optimal but viable",
    ],
    metaBuilds: [
      {
        name: "Aegis of Valor Fist of the Heavens",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "Smite enemies with holy lightning bolts that chain between targets. Beginner-friendly with high damage output. Excellent for Nephalem Rifts, Bounties, and pushing Greater Rifts.",
        keyItems: ["Aegis of Valor (6-piece)", "Darklight", "Khassett's Cord of Righteousness", "Norvald's Fervor", "Heaven's Fury"],
      },
      {
        name: "Akkhan Condemn",
        tier: "S",
        playstyle: "GR Push",
        description:
          "Commands spectral soldiers while detonating massive holy explosions with Condemn. Maintains permanent Akarat's Champion for near-invincibility and massive damage.",
        keyItems: ["Armor of Akkhan (6-piece)", "Blade of Prophecy", "Unrelenting Phalanx", "Captain Crimson's Trimmings"],
      },
      {
        name: "LoD Bombardment",
        tier: "A",
        playstyle: "GR Push",
        description:
          "Calls down devastating bombardments from the sky using the Belt of the Trove for automation. The Legacy of Dreams gem replaces a set, allowing more flexibility in item choices.",
        keyItems: ["Legacy of Dreams gem", "The Mortal Drama", "Belt of the Trove", "Illusory Boots", "Faithful Memory"],
      },
    ],
    abilities: [
      { name: "Punish", type: "Primary", element: "Holy", description: "Strike enemies and gain Hardened Senses, increasing Block Chance. The go-to primary skill for most builds." },
      { name: "Shield Bash", type: "Secondary", element: "Holy", description: "Charge and bash enemies with your shield, dealing damage based on Block Chance. Core to shield-focused builds." },
      { name: "Fist of the Heavens", type: "Secondary", element: "Lightning", description: "Calls down a bolt of holy lightning that chains between enemies. The centerpiece of the Aegis of Valor build." },
      { name: "Heaven's Fury", type: "Secondary", element: "Fire", description: "Calls down a beam of holy fire from the heavens. Synergizes powerfully with the Aegis of Valor set." },
      { name: "Condemn", type: "Utility", element: "Holy", description: "Builds up a massive holy explosion over 3 seconds. Core to the Akkhan Condemn build with Blade of Prophecy." },
      { name: "Bombardment", type: "Conviction", element: "Fire", description: "Calls in a rain of burning pitch and stone. Automated by Belt of the Trove in the LoD Bombardment build." },
      { name: "Akarat's Champion", type: "Conviction", element: "Holy", description: "Explodes with divine power, massively increasing damage and Wrath regeneration. Maintained permanently in most builds." },
      { name: "Laws of Valor", type: "Laws", element: "None", description: "Passively increases Attack Speed; active use empowers the effect. Used in most Crusader builds for the damage boost." },
      { name: "Shield Glare", type: "Defensive", element: "Holy", description: "Blinds all enemies in front of you. Used for crowd control and to proc the Blind debuff for certain builds." },
      { name: "Falling Sword", type: "Conviction", element: "Holy", description: "Launch into the heavens and crash down on enemies. Used for mobility and as a damage skill in some builds." },
    ],
    levelingTips: {
      early: [
        "Use Punish as your primary skill — the Retaliate rune adds a free counter-attack.",
        "Equip a shield as soon as possible; Block Chance scales several Crusader skills.",
        "Laws of Valor provides a consistent damage boost — use it from the moment it unlocks.",
        "Sweep Attack is excellent for clearing dense packs early on.",
        "Prioritize Strength and Vitality on gear; Crusaders are naturally tanky but need damage to progress.",
      ],
      mid: [
        "Unlock and use Akarat's Champion — even at low ranks, the damage and Wrath regen are significant.",
        "Start using Condemn or Heaven's Fury as your main damage skill depending on your gear.",
        "The Heavenly Strength passive (level 16) lets you wield a two-handed weapon with a shield — a massive damage boost.",
        "Look for Flails with high damage — they are the Crusader's best-in-slot weapon type.",
        "Equip Iron Skin for emergency survivability in tough situations.",
      ],
      late: [
        "Complete Season Journey chapters II–IV to receive Haedrig's Gift (Aegis of Valor set recommended).",
        "With the Aegis of Valor 2-piece, Fist of the Heavens becomes dramatically more powerful.",
        "Run Master difficulty Bounties to collect Horadric Cache materials for Kanai's Cube recipes.",
        "Use Kanai's Cube to upgrade Rare Flails into Legendaries — the Darklight is your primary target.",
        "Transition to Torment difficulties as soon as your set bonuses are active.",
      ],
      endgame: [
        "Maintain permanent Akarat's Champion uptime — this is the most important mechanical requirement.",
        "In Aegis of Valor, alternate between Fist of the Heavens and Heaven's Fury for maximum synergy.",
        "Cooldown Reduction is the most important secondary stat for most Crusader builds.",
        "Use Norvald's Fervor (Flail + Shield set) to maintain permanent Steed Charge uptime for mobility.",
        "In group play, Crusaders provide Laws buffs — coordinate with your team on which Law to use.",
      ],
    },
    masteryNote:
      "The Crusader's unique ability to equip a two-handed weapon in one hand (via Heavenly Strength) while holding a shield in the other is unmatched in the game. Mastering Cooldown Reduction to maintain permanent Akarat's Champion is the key to unlocking the class's full potential.",
    masteryTips: [
      "Aim for 37–56% Cooldown Reduction to maintain permanent Akarat's Champion uptime.",
      "In Aegis of Valor, the rotation is: cast Fist of the Heavens → Heaven's Fury activates → repeat. Never stop casting.",
      "Blade of Prophecy makes Condemn hit all enemies within 15 yards — position yourself at the center of packs.",
      "Use Illusory Boots in LoD Bombardment to walk through enemies and position Bombardment optimally.",
      "In group play, always use Laws of Valor with the Unstoppable Force rune to reduce skill costs for your team.",
    ],
    paragons: [
      { category: "Core", priority: ["Movement Speed (cap at 25%)", "Strength (infinite)"] },
      { category: "Offense", priority: ["Cooldown Reduction (50 pts — critical)", "Critical Hit Damage (50 pts)", "Critical Hit Chance (50 pts)"] },
      { category: "Defense", priority: ["Armor (50 pts)", "Life % (50 pts)", "All Resistance (50 pts)"] },
      { category: "Utility", priority: ["Area Damage (50 pts)", "Resource Cost Reduction (50 pts)"] },
    ],
  },
  {
    id: "demon-hunter",
    name: "Demon Hunter",
    tagline: "Relentless Pursuer of the Darkness",
    overview:
      "Demon Hunters are ranged specialists who combine crossbows, magical devices, and traps to hunt the demons that destroyed their lives. They utilize a unique dual-resource system — Hatred for offense and Discipline for defense — requiring constant resource management. Masters of mobility, they are always moving, always repositioning, and always dealing damage from a safe distance.",
    primaryStat: "Dexterity",
    resource: {
      name: "Hatred / Discipline",
      description:
        "Hatred is the primary offensive resource, regenerating passively and through Primary skills. Discipline is the secondary defensive resource, regenerating very slowly and used for movement and utility skills. Managing both simultaneously is the defining challenge of the Demon Hunter.",
    },
    color: "#8e44ad",
    colorName: "Shadow Violet",
    bgGradient: "linear-gradient(135deg, #0d0014 0%, #1e0033 50%, #0d0014 100%)",
    weaponTypes: [
      "Hand Crossbows — one-handed, can dual-wield for attack speed; many build-defining legendaries",
      "Crossbows — two-handed, highest damage per shot",
      "Bows — two-handed, balanced attack speed and damage",
      "Quivers — off-hand item with Attack Speed and skill bonuses",
    ],
    metaBuilds: [
      {
        name: "Gears of Dreadlands Hungering Arrow",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "An extremely mobile build using Strafe to automatically fire Hungering Arrow projectiles. Easy to play with a high skill ceiling. The Ninth Cirri Satchel makes arrows pierce and bounce, multiplying damage exponentially.",
        keyItems: ["Gears of Dreadlands (6-piece)", "The Ninth Cirri Satchel", "Hunter's Wrath", "Depth Diggers", "Odyssey's End"],
      },
      {
        name: "Shadow Impale",
        tier: "S",
        playstyle: "GR Push",
        description:
          "A melee-range assassin build that uses Impale for massive single-target and AoE burst damage. Requires getting close to enemies, making positioning and Smoke Screen timing critical.",
        keyItems: ["The Shadow's Mantle (6-piece)", "Karlei's Point", "Holy Point Shot", "Elusive Ring", "Dawn"],
      },
      {
        name: "Embodiment of the Marauder Sentry",
        tier: "A",
        playstyle: "GR Push",
        description:
          "Places Sentries that fire Cluster Arrow or Multishot, dealing massive AoE damage. A slower, more strategic playstyle that rewards good positioning and cooldown management.",
        keyItems: ["Embodiment of the Marauder (6-piece)", "Zoey's Secret", "The Cloak of Garwulf", "Dawn", "Hellcat Waistguard"],
      },
    ],
    abilities: [
      { name: "Hungering Arrow", type: "Primary", element: "Physical", description: "Fires a seeking arrow that pierces through enemies. The core skill of the GoD build — The Ninth Cirri Satchel makes it bounce between targets." },
      { name: "Impale", type: "Hatred Spender", element: "Physical", description: "Throws a massive knife dealing devastating single-target damage. The core skill of the Shadow Impale build." },
      { name: "Multishot", type: "Hatred Spender", element: "Physical", description: "Fires a massive volley of arrows hitting all enemies in a wide arc. Excellent AoE damage for speedfarming." },
      { name: "Cluster Arrow", type: "Hatred Spender", element: "Fire", description: "Fires an explosive cluster that deals massive AoE damage. The primary skill in Marauder Sentry builds." },
      { name: "Strafe", type: "Hatred Spender", element: "Physical", description: "Continuously fires arrows while moving. In GoD builds, this automatically fires Hungering Arrows via the set bonus." },
      { name: "Vault", type: "Discipline", element: "None", description: "Tumbles to a new location, providing brief immunity during animation. The primary mobility skill — use it constantly." },
      { name: "Smoke Screen", type: "Discipline", element: "None", description: "Vanishes in a cloud of smoke, becoming invincible for its duration. Critical for surviving in Shadow Impale builds." },
      { name: "Vengeance", type: "Archery", element: "Cold", description: "Transforms into a demonic form, granting crowd-control immunity and 40% multiplicative damage. Maintained permanently with Dawn." },
      { name: "Preparation", type: "Discipline", element: "None", description: "Restores Discipline. Used with Focused Mind or Invigoration runes to maintain Discipline for Vault and Smoke Screen." },
      { name: "Sentry", type: "Devices", element: "Physical", description: "Places a turret that fires Hatred Spenders. The core mechanic of Marauder builds — each Sentry activates the set bonus." },
    ],
    levelingTips: {
      early: [
        "Use Hungering Arrow as your primary skill — it seeks enemies automatically, making it forgiving for beginners.",
        "Equip Vault immediately when it unlocks — mobility is your primary survival tool.",
        "Use Caltrops and Spike Trap for area denial while you reposition.",
        "Multishot is excellent for clearing dense packs of weak enemies.",
        "Prioritize Dexterity on all gear — it directly increases your damage output.",
      ],
      mid: [
        "Unlock Vengeance and use it on cooldown — even without Dawn, the damage boost is significant.",
        "Start managing your dual resources consciously: save Discipline for emergencies, spend Hatred freely.",
        "Companion (Bat) provides Hatred regeneration — use it to sustain longer fights.",
        "Look for Hand Crossbows with high damage and attack speed for the fastest leveling.",
        "Use Preparation with the Punishment rune to convert Discipline into Hatred when needed.",
      ],
      late: [
        "Complete Season Journey chapters to receive Haedrig's Gift — GoD or Shadow's Mantle are both excellent.",
        "Dawn (Hand Crossbow) is your most important legendary — it reduces Vengeance cooldown by 65%, enabling permanent uptime.",
        "Use Kanai's Cube to upgrade Rare Hand Crossbows targeting Dawn and Karlei's Point.",
        "The Elusive Ring (Shadow Impale) provides massive damage reduction while Smoke Screen is active.",
        "Transition to Torment VI once you have your 4-piece set bonus active.",
      ],
      endgame: [
        "In GoD builds, always keep Strafe active — stopping breaks the momentum buff from the set.",
        "Maintain permanent Vengeance uptime using Dawn in Kanai's Cube or equipped.",
        "Stack Critical Hit Chance, Critical Hit Damage, and Elemental Damage on gear.",
        "In Shadow Impale, use Smoke Screen aggressively — it resets Impale's cooldown via Karlei's Point.",
        "For Marauder Sentry, place Sentries at choke points and let them do the work while you maintain Vengeance.",
      ],
    },
    masteryNote:
      "The Demon Hunter's dual-resource system is deceptively deep. Discipline is precious — wasting it on unnecessary Vaults when Smoke Screen would be more efficient is a common mistake. True mastery means never running out of either resource at a critical moment.",
    masteryTips: [
      "In GoD, the Momentum buff from Strafe stacks up to 15 times — never stop moving or you lose your damage.",
      "Shadow Impale requires getting within melee range — use Smoke Screen offensively, not just defensively.",
      "Odyssey's End (Marauder) makes enemies take 60% more damage when Entangled — always apply it before Sentries fire.",
      "Use Preparation with the Punishment rune as an emergency Hatred dump when Discipline is full.",
      "In group play, Demon Hunters provide the highest single-target damage — focus on Rift Guardians and elites.",
    ],
    paragons: [
      { category: "Core", priority: ["Movement Speed (cap at 25%)", "Dexterity (infinite)"] },
      { category: "Offense", priority: ["Critical Hit Damage (50 pts)", "Critical Hit Chance (50 pts)", "Attack Speed (GoD builds)", "Cooldown Reduction (Vengeance uptime)"] },
      { category: "Defense", priority: ["Life % (50 pts)", "Armor (50 pts)", "All Resistance (50 pts)"] },
      { category: "Utility", priority: ["Area Damage (50 pts)", "Resource Cost Reduction (50 pts)"] },
    ],
  },
  {
    id: "monk",
    name: "Monk",
    tagline: "Sacred Warrior of the Seven-Sided Path",
    overview:
      "Monks are sacred warriors who channel divine power through sheer force of will. Masters of hand-to-hand combat, they possess unparalleled mobility — darting in and out of melees with healing waves, protective mantras, and holy-empowered attacks. Their speed and versatility make them excellent both as damage dealers and as support characters in group play.",
    primaryStat: "Dexterity",
    resource: {
      name: "Spirit",
      description:
        "Spirit does not regenerate automatically — it is generated by Primary skills, completing attack combos, and specific items. Many Monk builds invest heavily in Spirit generation through skills like Epiphany or Resource Cost Reduction items to sustain their Spirit spenders.",
    },
    color: "#e67e22",
    colorName: "Sacred Amber",
    bgGradient: "linear-gradient(135deg, #1a0d00 0%, #3d2000 50%, #1a0d00 100%)",
    weaponTypes: [
      "Fist Weapons — Monk-exclusive, fastest attack speed, many build-defining legendaries",
      "Daibos — two-handed Monk-exclusive, high damage with unique legendary affixes",
      "One-handed Melee Weapons (Swords, Axes, Maces) — less optimal but viable",
      "Shields — usable but rarely optimal; most builds prefer dual-wield or Daibo",
    ],
    metaBuilds: [
      {
        name: "Inna Mystic Ally",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "Buffs Mystic Allies to deal devastating damage. The Fire variant excels in Greater Rifts while the Cold variant dominates T16 speedfarming. Relies on pet AI but is extremely powerful.",
        keyItems: ["Inna's Mantra (6-piece)", "The Crudest Boots", "Bindings of the Lesser Gods", "Lefebvre's Soliloquy"],
      },
      {
        name: "Sunwuko Tempest Rush",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "Channels Tempest Rush through enemy packs, triggering massive Sweeping Wind explosions. Extremely fun and mobile with strong damage output for both solo and group content.",
        keyItems: ["Monkey King's Garb (6-piece)", "Won Khim Lau", "Balance", "Cesar's Memento", "Kyoshiro's Soul"],
      },
      {
        name: "LoD Wave of Light",
        tier: "A",
        playstyle: "GR Push",
        description:
          "Drops massive bells on enemies using Wave of Light, amplified by numerous damage multipliers. The Legacy of Dreams gem replaces a set, allowing flexible item combinations.",
        keyItems: ["Legacy of Dreams gem", "Incense Torch of the Grand Temple", "Kyoshiro's Blade", "Pinto's Pride", "Tzo-Krin's Gaze"],
      },
    ],
    abilities: [
      { name: "Fists of Thunder", type: "Primary", element: "Lightning", description: "Teleports to targets and unleashes fast punches. Every third hit deals increased damage. Generates Spirit rapidly with the Quickening rune." },
      { name: "Tempest Rush", type: "Spirit Spender", element: "Fire", description: "Channels a rushing tornado through enemies. The core skill of the Sunwuko build — never stop moving." },
      { name: "Wave of Light", type: "Spirit Spender", element: "Fire", description: "Drops a massive bell on enemies dealing heavy AoE damage. The core skill of the LoD WoL build." },
      { name: "Lashing Tail Kick", type: "Spirit Spender", element: "Physical", description: "A powerful roundhouse kick dealing AoE damage. Used in several speedfarming builds." },
      { name: "Dashing Strike", type: "Technique", element: "Physical", description: "Quickly dashes up to 50 yards. Has multiple charges and is the primary mobility skill for all Monk builds." },
      { name: "Exploding Palm", type: "Technique", element: "Physical", description: "Applies a bleed; if the enemy dies while bleeding, it explodes for massive AoE damage. Core to group play Monk builds." },
      { name: "Sweeping Wind", type: "Technique", element: "Fire", description: "Surrounds the Monk in a damage vortex. Refreshed by melee attacks and stacks for increased damage in Sunwuko builds." },
      { name: "Cyclone Strike", type: "Focus", element: "Holy", description: "Pulls nearby enemies toward the Monk and blasts them. Excellent for grouping enemies for AoE damage." },
      { name: "Epiphany", type: "Focus", element: "Fire", description: "Increases Spirit regeneration and allows melee attacks to instantly dash to targets. Critical for resource management." },
      { name: "Inner Sanctuary", type: "Defensive", element: "Holy", description: "Creates a protective circle reducing damage taken. Essential for the support Monk role in group play." },
    ],
    levelingTips: {
      early: [
        "Use Exploding Palm for AoE damage — trigger explosions with Sweeping Wind or Lashing Tail Kick.",
        "Fists of Thunder is your best primary skill for Spirit generation, especially with the Quickening rune.",
        "Dashing Strike unlocks at level 9 — use it constantly for mobility and engaging packs.",
        "Mantra of Salvation provides early protection; switch to Mantra of Healing for Spirit regeneration later.",
        "Gamble Blood Shards on Boots (The Crudest Boots) and Bracers (Gungdo Gear) for powerful early legendaries.",
      ],
      mid: [
        "Integrate Sweeping Wind with the Inner Storm rune for sustained AoE and Spirit regeneration.",
        "Unlock the Harmony passive at level 45 — it converts a single resistance to All Resistance, dramatically improving toughness.",
        "Epiphany is a game-changer for Spirit management — use it on cooldown.",
        "Look for Fist Weapons and Daibos with high damage and Dexterity.",
        "Cyclone Strike is excellent for grouping enemies before your AoE skills detonate them.",
      ],
      late: [
        "Complete Season Journey chapters II–IV for Haedrig's Gift (Inna's Mantra is the typical season reward).",
        "With Inna's 2-piece, Mystic Allies become significantly stronger — start building around them.",
        "The Crudest Boots doubles your Mystic Ally count — this is your most important item.",
        "Use Kanai's Cube to upgrade Rare Fist Weapons targeting build-specific legendaries.",
        "Transition to Torment VI once your 4-piece set bonus is active.",
      ],
      endgame: [
        "In Tempest Rush builds, never stop channeling — the Sunwuko set bonus requires constant movement.",
        "Epiphany with the Desert Shroud rune provides 50% damage reduction — use it on cooldown.",
        "In group play, Monks provide Inner Sanctuary and Cyclone Strike for crowd control and grouping.",
        "Bindings of the Lesser Gods (Mystic Ally builds) doubles damage when enemies are in a Cyclone Strike vortex.",
        "Wave of Light builds require precise positioning — drop bells directly on elite packs for maximum damage.",
      ],
    },
    masteryNote:
      "The Monk's unparalleled mobility is their greatest asset. True mastery means never standing still — constantly dashing between packs, pulling enemies together with Cyclone Strike, and maintaining all buffs simultaneously while dealing damage.",
    masteryTips: [
      "In Tempest Rush, the Cesar's Memento bracers require you to hit enemies with a different skill first — always open with Dashing Strike.",
      "Exploding Palm's explosion radius is massive — in group play, one detonation can clear an entire screen.",
      "The Crudest Boots doubles Mystic Ally count — position them strategically around elite packs.",
      "Epiphany's Desert Shroud rune provides 50% damage reduction — never let it drop off.",
      "In Wave of Light, the Incense Torch of the Grand Temple reduces cost by 75% — stack Resource Cost Reduction for near-free casts.",
    ],
    paragons: [
      { category: "Core", priority: ["Movement Speed (cap at 25%)", "Dexterity (infinite)"] },
      { category: "Offense", priority: ["Critical Hit Damage (50 pts)", "Critical Hit Chance (50 pts)", "Cooldown Reduction (Epiphany)", "Attack Speed (situational)"] },
      { category: "Defense", priority: ["Armor (50 pts)", "Life % (50 pts)", "All Resistance (50 pts)"] },
      { category: "Utility", priority: ["Area Damage (50 pts)", "Resource Cost Reduction (50 pts)"] },
    ],
  },
  {
    id: "necromancer",
    name: "Necromancer",
    tagline: "Custodian of the Balance Between Life and Death",
    overview:
      "Necromancers are masters of dark arts, commanding hordes of the dead, crushing enemies with bone and blood spells, and debilitating foes with curses. They are strategic commanders who control the battlefield through grim will and calculated use of life and death magic. Uniquely, they can sacrifice their own health to power their most devastating abilities.",
    primaryStat: "Intelligence",
    resource: {
      name: "Essence",
      description:
        "Essence is capped at 200 and does not regenerate passively — it is generated by hitting enemies with Primary skills. Unlike other resources, Essence does not decay over time, allowing for careful accumulation before unleashing powerful spenders.",
    },
    color: "#27ae60",
    colorName: "Bone Green",
    bgGradient: "linear-gradient(135deg, #001a08 0%, #003d15 50%, #001a08 100%)",
    weaponTypes: [
      "Scythes (one-handed) — Necromancer-exclusive, most powerful legendary affixes",
      "Two-Handed Scythes — massive damage, often used with Phylactery off-hand",
      "Phylacteries — off-hand item with unique Necromancer-specific legendary powers",
      "Shields — usable but rarely optimal for damage builds",
    ],
    metaBuilds: [
      {
        name: "Masquerade Bone Spear",
        tier: "S",
        playstyle: "GR Push",
        description:
          "Fires devastating bone spears amplified by Simulacrums (mirror images). Fast-paced with tremendous AoE damage. Requires precise positioning to maximize the piercing projectile's impact.",
        keyItems: ["Masquerade of the Burning Carnival (6-piece)", "Gelmindor's Marrow Guards", "Briggs' Wrath", "Simulacrum"],
      },
      {
        name: "LoD Death Nova",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "Unleashes explosive Death Novas that obliterate screens of enemies. Excellent AoE but struggles with single targets. The Legacy of Dreams gem provides the damage multiplier.",
        keyItems: ["Legacy of Dreams gem", "Funerary Pick", "Iron Rose", "Bloodtide Blade", "Nemesis Bracers"],
      },
      {
        name: "Trag'Oul Death Nova",
        tier: "A",
        playstyle: "GR Push",
        description:
          "Similar to LoD Death Nova but with increased survivability from the Trag'Oul set bonuses. Strong AoE damage with better sustain, ideal for players learning the Death Nova playstyle.",
        keyItems: ["Trag'Oul's Avatar (6-piece)", "Funerary Pick", "Iron Rose", "Bloodtide Blade"],
      },
    ],
    abilities: [
      { name: "Bone Spikes", type: "Primary", element: "Physical", description: "Summons bone spikes from the ground dealing Physical damage and generating Essence. The standard primary skill for most builds." },
      { name: "Grim Scythe", type: "Primary", element: "Physical", description: "Slashes with a summoned scythe in front of you. Hits multiple enemies and generates significant Essence per hit." },
      { name: "Bone Spear", type: "Secondary", element: "Physical", description: "Fires a piercing projectile through all enemies in a line. The core skill of the Masquerade build — Simulacrums multiply its damage." },
      { name: "Death Nova", type: "Secondary", element: "Poison", description: "Unleashes a nova of necrotic energy damaging all nearby enemies. The core skill of both LoD and Trag'Oul Death Nova builds." },
      { name: "Corpse Explosion", type: "Corpses", element: "Physical", description: "Detonates up to 5 corpses simultaneously, dealing massive AoE damage. Requires corpses — use Simulacrum or Bone Armor to generate them." },
      { name: "Command Skeletons", type: "Reanimation", element: "Physical", description: "Passively raises skeletons and commands them to focus targets. The core skill of summoner builds." },
      { name: "Skeletal Mage", type: "Secondary", element: "Physical", description: "Raises a powerful skeletal mage that attacks enemies. Used in Rathma and LoD summoner builds." },
      { name: "Bone Armor", type: "Blood & Bone", element: "Physical", description: "Rips bones from nearby enemies to create protective armor. Provides damage reduction and generates corpses for Corpse Explosion." },
      { name: "Blood Rush", type: "Blood & Bone", element: "Physical", description: "Teleports up to 50 yards by shedding mortal flesh. The primary mobility skill — costs a percentage of maximum Life." },
      { name: "Land of the Dead", type: "Reanimation", element: "Physical", description: "Raises a massive army from the dead for 5 seconds, enabling unlimited Corpse skills. The ultimate cooldown for burst damage." },
    ],
    levelingTips: {
      early: [
        "Use Corpse Explosion for efficient mob clearing — it deals massive AoE damage when corpses are available.",
        "Bone Spikes is your primary Essence generator — use it to fuel your spenders.",
        "Command Skeletons provides free damage and acts as a distraction for enemies.",
        "Prioritize Intelligence and Vitality on gear for damage and survivability.",
        "Blood Rush is your escape tool — always keep it available for emergencies.",
      ],
      mid: [
        "Experiment with Bone Spear as your primary damage skill — it pierces through multiple enemies.",
        "Simulacrum (unlocks at level 50) is a game-changer — it mirrors your skills for massive damage multiplication.",
        "Start looking for Scythes with high damage and Intelligence for maximum output.",
        "Bone Armor provides significant damage reduction — use it on cooldown.",
        "Land of the Dead enables burst damage windows — save it for elite packs and Rift Guardians.",
      ],
      late: [
        "Complete Season Journey chapters II–IV for Haedrig's Gift (Masquerade or Trag'Oul are common season rewards).",
        "Gelmindor's Marrow Guards (Masquerade) makes Simulacrum Bone Spears deal 300% more damage — your top priority item.",
        "Use Kanai's Cube to upgrade Rare Scythes targeting Funerary Pick or Briggs' Wrath.",
        "Transition to Torment VI once your 4-piece set bonus is active.",
        "Nemesis Bracers are universally useful — equip them or extract the power via Kanai's Cube.",
      ],
      endgame: [
        "In Masquerade Bone Spear, position yourself so Bone Spears pierce through as many enemies as possible.",
        "Land of the Dead is your burst window — save Essence and cooldowns for when it's active.",
        "Corpse generation is critical — Bone Armor and Simulacrum both generate corpses for Corpse Explosion.",
        "In Death Nova builds, stay in the center of enemy packs — the nova hits all surrounding enemies.",
        "Stack Intelligence, Critical Hit Chance, and Critical Hit Damage on all gear pieces.",
      ],
    },
    masteryNote:
      "The Necromancer's unique mechanic is corpse management. Corpses can be consumed for Essence, exploded for AoE damage, or raised as minions. Mastering when to generate, save, and spend corpses is what separates a good Necromancer from a great one.",
    masteryTips: [
      "In Masquerade Bone Spear, Simulacrums cast their own Bone Spears — position yourself so all three pierce the same pack.",
      "Land of the Dead enables unlimited Corpse Explosion — pre-stack Essence before activating it for maximum burst.",
      "Briggs' Wrath pulls enemies to you when you cast Bone Spear — use it to group enemies before your AoE.",
      "Bone Armor generates a corpse for each enemy hit — use it in dense packs to fuel Corpse Explosion.",
      "In group play, Necromancers provide Frailty (Aura of Frailty) for a 15% damage amplification to all enemies.",
    ],
    paragons: [
      { category: "Core", priority: ["Movement Speed (cap at 25%)", "Intelligence (infinite)"] },
      { category: "Offense", priority: ["Critical Hit Damage (50 pts)", "Critical Hit Chance (50 pts)", "Cooldown Reduction (Land of the Dead)", "Attack Speed (situational)"] },
      { category: "Defense", priority: ["Armor (50 pts)", "Life % (50 pts)", "All Resistance (50 pts)"] },
      { category: "Utility", priority: ["Area Damage (50 pts)", "Resource Cost Reduction (50 pts)"] },
    ],
  },
  {
    id: "witch-doctor",
    name: "Witch Doctor",
    tagline: "Voice of the Spirits, Master of the Undying",
    overview:
      "Witch Doctors are spiritual warriors who summon dead souls and crawling creatures to do their bidding. They control the battlefield with hexes, curses, and pets, assaulting enemies with various elemental attacks. Their playstyle revolves around outsmarting foes, rendering them helpless, and letting their summoned allies or devastating curses finish them off.",
    primaryStat: "Intelligence",
    resource: {
      name: "Mana",
      description:
        "Mana is a vast but slowly-regenerating resource. Witch Doctors must manage it carefully, relying on summoned creatures and free Primary attacks to conserve it while their powerful spells recharge. Several builds invest in Mana regeneration or use free-cost skills to avoid depletion.",
    },
    color: "#16a085",
    colorName: "Voodoo Teal",
    bgGradient: "linear-gradient(135deg, #001a14 0%, #003d2a 50%, #001a14 100%)",
    weaponTypes: [
      "Ceremonial Knives — Witch Doctor-exclusive, most build-defining legendary affixes (Sacred Harvester, The Barber, Voo's Juicer)",
      "Staves — several important staves like Wormwood, Staff of Chiroptera, and SuWong Diviner",
      "Mojos — off-hand item with unique Witch Doctor-specific legendary powers",
      "One-handed Swords, Axes, Maces — less optimal but viable with the right legendary affixes",
    ],
    metaBuilds: [
      {
        name: "Mundunugu Spirit Barrage",
        tier: "S",
        playstyle: "GR Push",
        description:
          "Focuses on releasing massive AoE Spirit Barrage bursts, dominating solo Greater Rift pushing. The Mundunugu set amplifies Spirit Barrage damage based on the number of enemies hit.",
        keyItems: ["Mundunugu's Regalia (6-piece)", "The Barber", "Gazing Demise", "Ring of Emptiness"],
      },
      {
        name: "Jade Harvester Haunt",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "Applies Haunt and Locust Swarm DoTs to enemies, then instantly converts all accumulated damage into burst damage with Soul Harvest. Extremely satisfying and powerful.",
        keyItems: ["Raiment of the Jade Harvester (6-piece)", "Ring of Emptiness", "Quetzalcoatl", "Sacred Harvester"],
      },
      {
        name: "Arachyr Corpse Spiders",
        tier: "A",
        playstyle: "Speedfarm / GR Push",
        description:
          "Spreads Corpse Spiders damage to all enemies infested by the Arachyr set. The Angry Chicken variant (Hex: Angry Chicken) is exceptional for speed farming due to its explosive mobility.",
        keyItems: ["Spirit of Arachyr (6-piece)", "The Spider Queen's Grasp", "Manajuma's Way", "Cluckeye"],
      },
    ],
    abilities: [
      { name: "Poison Dart", type: "Primary", element: "Poison", description: "Fires a deadly dart dealing Poison damage over time. The standard primary skill for Mana generation." },
      { name: "Spirit Barrage", type: "Mana Spender", element: "Physical", description: "Unleashes a barrage of spirit bolts. The core skill of the Mundunugu build — The Barber stores damage for a massive delayed explosion." },
      { name: "Haunt", type: "Mana Spender", element: "Cold", description: "Haunts an enemy with a spirit that deals Cold damage over time. Core to the Jade Harvester build — apply to all enemies before Soul Harvest." },
      { name: "Locust Swarm", type: "Mana Spender", element: "Poison", description: "Unleashes a plague of locusts that spreads between enemies. Pairs with Haunt in Jade Harvester builds for maximum DoT stacking." },
      { name: "Soul Harvest", type: "Terror", element: "Physical", description: "Feeds on the life force of nearby enemies, gaining Intelligence. In Jade Harvester, instantly converts all DoT damage into burst damage." },
      { name: "Corpse Spiders", type: "Secondary", element: "Physical", description: "Throws a jar of spiders that attack nearby enemies. The core skill of the Arachyr build — The Spider Queen's Grasp amplifies their damage." },
      { name: "Gargantuan", type: "Voodoo", element: "Physical", description: "Summons a massive zombie to fight for you. Used in summoner builds and as a damage boost in several meta builds." },
      { name: "Spirit Walk", type: "Defensive", element: "None", description: "Leaves the physical body to enter the spirit realm, becoming invincible and moving freely. The primary survival skill." },
      { name: "Hex", type: "Utility", element: "None", description: "Transforms enemies into harmless chickens. The Angry Chicken rune transforms the Witch Doctor for explosive mobility in the Arachyr build." },
      { name: "Piranhas", type: "Decay", element: "Poison", description: "Summons a pool of piranhas dealing Poison damage and increasing damage taken by affected enemies by 15%." },
    ],
    levelingTips: {
      early: [
        "Focus on summoning skills — Summon Zombie Dogs and Gargantuan provide free damage and act as meat shields.",
        "Use Haunt and Acid Cloud for supplementary damage while your pets do the heavy lifting.",
        "Spirit Walk is your primary survival tool — use it to escape dangerous situations.",
        "Unlock Spirit Vessel (level 30) — it provides a free death every 60 seconds, dramatically improving survivability.",
        "Fetish Sycophants (level 30) passively summons Fetishes when you cast spells — a significant free damage boost.",
      ],
      mid: [
        "Incorporate Fierce Loyalty (level 45) and Grave Injustice (level 50) passives for pet buffs.",
        "Switch Spirit Walk to the Severance rune at level 47 for faster movement during Spirit Walk.",
        "Soul Harvest provides a significant Intelligence buff — use it on cooldown near enemy packs.",
        "Look for Ceremonial Knives with high damage and Intelligence for maximum output.",
        "Piranhas provides a 15% damage amplification — apply it to all elite packs before spending Mana.",
      ],
      late: [
        "Complete Season Journey chapters II–IV for Haedrig's Gift (Jade Harvester or Mundunugu are common rewards).",
        "The Ring of Emptiness doubles damage against enemies affected by Haunt or Locust Swarm — your top priority item.",
        "Use Kanai's Cube to upgrade Rare Ceremonial Knives targeting Sacred Harvester or The Barber.",
        "Transition to Torment VI once your 4-piece set bonus is active.",
        "Quetzalcoatl doubles Soul Harvest damage — equip it or extract its power via Kanai's Cube.",
      ],
      endgame: [
        "In Jade Harvester, apply Haunt and Locust Swarm to all enemies before Soul Harvesting for maximum burst.",
        "Ring of Emptiness requires enemies to be affected by both Haunt AND Locust Swarm for the full 200% bonus.",
        "In Mundunugu, The Barber stores Spirit Barrage damage for 2 seconds then releases it all at once — position carefully.",
        "Spirit Walk is your emergency escape — never waste it on trivial situations.",
        "In Arachyr Angry Chicken, use Hex: Angry Chicken to travel between packs at extreme speed, then detonate on arrival.",
      ],
    },
    masteryNote:
      "The Jade Harvester build's DoT-to-burst mechanic is one of the most unique in the game. Mastering the rhythm of applying Haunt and Locust Swarm to entire screens of enemies before triggering Soul Harvest for an instant kill is deeply satisfying and highly effective.",
    masteryTips: [
      "In Jade Harvester, the Sacred Harvester increases Soul Harvest stacks to 10 — always maintain maximum stacks.",
      "Ring of Emptiness requires BOTH Haunt and Locust Swarm on the target — apply both before spending Mana.",
      "In Arachyr Angry Chicken, the explosion radius is massive — detonate in the center of the largest pack.",
      "Piranhas with the Piranhado rune pulls enemies together — use it before any AoE skill for maximum efficiency.",
      "In group play, Witch Doctors provide Piranhas for grouping and Ring of Emptiness for a team-wide damage amplification.",
    ],
    paragons: [
      { category: "Core", priority: ["Movement Speed (cap at 25%)", "Intelligence (infinite)"] },
      { category: "Offense", priority: ["Critical Hit Damage (50 pts)", "Critical Hit Chance (50 pts)", "Cooldown Reduction (Soul Harvest)", "Attack Speed (situational)"] },
      { category: "Defense", priority: ["Armor (50 pts)", "Life % (50 pts)", "All Resistance (50 pts)"] },
      { category: "Utility", priority: ["Area Damage (50 pts)", "Resource Cost Reduction (50 pts)"] },
    ],
  },
  {
    id: "wizard",
    name: "Wizard",
    tagline: "Renegade Arcanist of Unlimited Power",
    overview:
      "Wizards are renegade arcanists who manipulate the raw forces of fire, ice, lightning, and arcane energy to obliterate their enemies. Masters of elemental destruction, they can freeze time, teleport across the battlefield, and unleash cataclysmic spells. Their fast-regenerating Arcane Power means they are rarely resource-starved, allowing them to maintain a constant barrage of devastating magic.",
    primaryStat: "Intelligence",
    resource: {
      name: "Arcane Power",
      description:
        "Arcane Power regenerates quickly on its own, making Wizards one of the least resource-constrained classes. It is generated by Primary skills and regenerates passively at a rate of 20 per second. Most builds have minimal resource management concerns.",
    },
    color: "#2980b9",
    colorName: "Arcane Blue",
    bgGradient: "linear-gradient(135deg, #000d1a 0%, #001f3d 50%, #000d1a 100%)",
    weaponTypes: [
      "Wands — Wizard-exclusive, fastest attack speed, many build-defining legendary affixes",
      "Swords, Daggers — one-handed options for dual-wield or off-hand combinations",
      "Two-Handed Staves — high damage, often with powerful legendary affixes",
      "Sources (off-hand) — Wizard-exclusive off-hand with unique legendary powers",
    ],
    metaBuilds: [
      {
        name: "Firebird Mirror Image",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "Ignites enemies with fire damage that spreads infinitely between burning targets. Mirror Images multiply the Firebird ignition stacks. One of the strongest builds in the game for both farming and pushing.",
        keyItems: ["Firebird's Finery (6-piece)", "Deathwish", "Etched Sigil", "Mirror Image", "Aquila Cuirass"],
      },
      {
        name: "Typhon Hydra",
        tier: "S",
        playstyle: "Speedfarm / GR Push",
        description:
          "Summons powerful Hydras that deal continuous fire damage. The Typhon set dramatically amplifies Hydra damage while reducing their cooldown. A strong and relatively straightforward build.",
        keyItems: ["Typhon's Veil (6-piece)", "Serpent's Sparker", "The Magistrate", "Etched Sigil"],
      },
      {
        name: "LoD Frozen Orb",
        tier: "A",
        playstyle: "Speedfarm / GR Push",
        description:
          "Launches massive Frozen Orbs that shatter on impact, dealing heavy cold damage to all nearby enemies. The Legacy of Dreams gem provides the damage multiplier without requiring a full set.",
        keyItems: ["Legacy of Dreams gem", "Halo of Karini", "The Oculus", "Manald Heal", "Triumvirate"],
      },
    ],
    abilities: [
      { name: "Magic Missile", type: "Primary", element: "Arcane", description: "Fires a seeking missile of arcane energy. The standard primary skill for Arcane Power generation." },
      { name: "Electrocute", type: "Primary", element: "Lightning", description: "Channels a beam of lightning that chains between nearby enemies. Excellent for generating Arcane Power against multiple targets." },
      { name: "Hydra", type: "Arcane Power Spender", element: "Fire", description: "Summons a multi-headed hydra that breathes fire. The core skill of the Typhon build — Serpent's Sparker allows two Hydras simultaneously." },
      { name: "Frozen Orb", type: "Arcane Power Spender", element: "Cold", description: "Launches a massive orb that explodes in a shower of ice shards. The core skill of the LoD Frozen Orb build." },
      { name: "Arcane Torrent", type: "Arcane Power Spender", element: "Arcane", description: "Channels a barrage of arcane bolts. Used in Etched Sigil builds to automatically cast other skills." },
      { name: "Disintegrate", type: "Arcane Power Spender", element: "Arcane", description: "Channels a beam of pure arcane energy that disintegrates everything in its path." },
      { name: "Teleport", type: "Utility", element: "Arcane", description: "Instantly teleports to a target location. The primary mobility skill — use it constantly for repositioning." },
      { name: "Mirror Image", type: "Conjuration", element: "None", description: "Creates mirror images that mimic your attacks. In Firebird builds, they generate ignition stacks independently." },
      { name: "Slow Time", type: "Utility", element: "Arcane", description: "Creates a bubble that slows time for enemies inside. Used for crowd control and to proc the Delsere's Magnum Opus set bonus." },
      { name: "Black Hole", type: "Arcane Power Spender", element: "Arcane", description: "Creates a singularity that pulls enemies together. Excellent for grouping enemies before AoE damage." },
    ],
    levelingTips: {
      early: [
        "Use Magic Missile or Electrocute as your primary skill for consistent Arcane Power generation.",
        "Teleport is your primary mobility skill — use it to escape dangerous situations and reposition.",
        "Arcane Torrent or Disintegrate are excellent channeled damage skills for early leveling.",
        "Frost Nova provides crowd control — freeze enemies before unleashing AoE damage.",
        "Prioritize Intelligence on all gear for maximum damage output.",
      ],
      mid: [
        "Unlock and use Hydra — even without the Typhon set, it provides significant passive damage.",
        "Mirror Image provides both offensive and defensive value — use it on cooldown.",
        "Black Hole is excellent for grouping enemies before your AoE skills detonate them.",
        "Look for Wands and Sources with high damage and Intelligence.",
        "Slow Time provides crowd control and can proc several powerful set bonuses.",
      ],
      late: [
        "Complete Season Journey chapters II–IV for Haedrig's Gift (Firebird's Finery or Typhon's Veil are common rewards).",
        "Etched Sigil (Source) automatically casts your secondary skill while channeling — your top priority item.",
        "Use Kanai's Cube to upgrade Rare Wands targeting Deathwish or Serpent's Sparker.",
        "Transition to Torment VI once your 4-piece set bonus is active.",
        "Deathwish increases damage by 325% while channeling — equip it or extract its power via Kanai's Cube.",
      ],
      endgame: [
        "In Firebird Mirror Image, maintain Mirror Images on cooldown — they independently generate ignition stacks.",
        "In Typhon Hydra, always have two Hydras active — Serpent's Sparker enables this.",
        "Stack Cold Damage on gear for Frozen Orb builds — elemental damage is a direct multiplier.",
        "The Oculus ring creates a zone that increases damage by 85% — always stand in it.",
        "In group play, Wizards provide Slow Time for crowd control and The Oculus ring buff for the entire team.",
      ],
    },
    masteryNote:
      "The Wizard's mastery lies in maximizing uptime on damage multipliers. Deathwish's 325% channeling bonus, Mirror Image's independent ignition stacks, and The Oculus ring's 85% damage zone must all be active simultaneously for peak performance.",
    masteryTips: [
      "In Firebird, Mirror Images die quickly — recast them constantly to maintain ignition stack generation.",
      "The Oculus ring creates a random damage zone — always reposition to stand in it when it appears.",
      "In Typhon Hydra, Etched Sigil automatically casts Hydra while you channel Arcane Torrent — never stop channeling.",
      "Deathwish requires channeling — Arcane Torrent or Disintegrate must be active for the 325% bonus.",
      "In group play, cast Slow Time on Rift Guardians — it provides a significant damage window for your team.",
    ],
    paragons: [
      { category: "Core", priority: ["Movement Speed (cap at 25%)", "Intelligence (infinite)"] },
      { category: "Offense", priority: ["Critical Hit Damage (50 pts)", "Critical Hit Chance (50 pts)", "Cooldown Reduction (Mirror Image)", "Attack Speed (situational)"] },
      { category: "Defense", priority: ["Armor (50 pts)", "Life % (50 pts)", "All Resistance (50 pts)"] },
      { category: "Utility", priority: ["Area Damage (50 pts)", "Resource Cost Reduction (50 pts)"] },
    ],
  },
];

export const classMap: Record<string, ClassData> = Object.fromEntries(
  classes.map((c) => [c.id, c])
);
